package-lock.json
package.json
src/i18n/cldr/load.ts
src/i18n/date.ts
src/i18n/i18n.ts
src/i18n/number.ts
src/i18n/unit.ts
src/i18n/util/globalize.ts

**Type:** bug
Removes the hack in the codebase for the old `@types/globalize` definitions and uses new version of typings with submodules defined.

Update @types/globalize to 0.0.34 and remove hack for old typings

---

package-lock.json
src/stores/README.md
src/stores/Store.ts
src/stores/StoreInjector.ts
tests/stores/unit/StoreInjector.ts

**Type:** bug
Adds support for functional selector for returning state `paths` used to determine if the `StoreContainer` invalidates. Meaning when data changes in the store for the paths returned.
The current static typings of `paths` only enables a consumer to go one level deep, these have been maintained for backwards compatibility.
**Todo:**
Resolves https://github.com/dojo/stores/issues/174

Enable functional selectors for `StoreContainer` paths

---

src/core/README.md
src/core/request/README.md
src/has/README.md
src/i18n/README.md
src/routing/README.md
src/shim/README.md
src/stores/README.md
src/testing/README.md
src/widget-core/README.md

* Updates all readme code references to use the new `@dojo/framework` import path
* Removes all the legacy badges from READMEs
* Removes contributing section the inner READMEs
* Removes the incorrect installation instructions

Update all the readmes after the move to framework

---

src/core/request/interfaces.d.ts
src/core/request/providers/node.ts
src/core/request/providers/xhr.ts
src/shim/AbortController.ts
src/shim/support/has.ts
tests/core/unit/request/node.ts
tests/core/unit/request/xhr.ts
tests/shim/unit/AbortController.ts
tests/shim/unit/all.ts
tests/shim/unit/support/has.ts

Resolves dojo/core#390
add support for a `signal: AbortSignal` property in the request options. When provided, the request can be aborted by calling the `AbortController#abort` method, similar to the fetch API. When a request is aborted, the `Promise` is rejected with an `AbortError`, if possible.

Abort controller signal to request and AbortController/AbortSignal shims

---

src/core/request/interfaces.d.ts
src/core/request/providers/xhr.ts
tests/core/unit/request/xhr.ts

Hook up credentials ReqestOptions option to tie into XHR's
withCredentials option
**Type:** bug / missing feature
`RequestOptions` currently has a `credentials` option, but it's not hooked up to anything. This PR changes that and ties it into the underlying XHR's `withCredentials` property.

hook up credentials RequestOptions to xhr

---

src/widget-core/tsx.ts
tests/widget-core/unit/tsx.ts

Adds a small registry type hack for lazy loading widgets via tsx. The companion build pr for this is here: https://github.com/dojo/webpack-contrib/pull/60

Add registry tsx type that transfers a registry id from a property

---

package-lock.json
src/widget-core/d.ts
tests/widget-core/unit/d.ts

Adds an overload for `v()` and `w()` that accepts an existing instead of a string tag/widget constructor that that will merge any properties onto the provided node and replace the nodes children with the provided children.
Resolves: #67

Add pragma to merge properties and replace children onto an existing vnode

---

package-lock.json
src/routing/ActiveLink.ts
src/routing/Link.ts
src/routing/README.md
src/routing/Router.ts
src/routing/interfaces.d.ts
tests/routing/unit/ActiveLink.ts
tests/routing/unit/Link.ts
tests/routing/unit/all.ts

Refactors the existing `Link` component and adds an `ActiveLink` component that applies classes when the link's outlet is "active".
Resolves: #61

ActiveLink that applies classes when the outlet is active

---

examples/routing/ambigious-matches.ts
examples/routing/basic.ts
examples/routing/main.ts
examples/routing/url-parameters.ts
src/routing/Outlet.ts
src/routing/README.md
src/routing/Router.ts
src/routing/interfaces.d.ts
tests/routing/unit/Outlet.ts
tests/routing/unit/Router.ts

This changes the `Outlet` from a higher order component to a standard component with a render property. The render property is used to display content when a route matches providing more control over the nodes to render when an Outlet's route has been matched.
Having an `Outlet` as a HOC implies that it would be shared across the application (which generally they are not), adds complexity in it's usage by having to specify another interface for the properties that the `Outlet` can accept and has more boilerplate and indirection that if the `Outlet` is a standard widget.
```ts
render() {
return v('div', [
w(Outlet, { 
id: 'outlet-name', 
renderer: (matchDetails: MatchDetails) => {
// match details contains the …
```

Convert `Outlet` from a HOC to a standard component with a render prop

---

package-lock.json
package.json
src/i18n/i18n.ts
src/shim/AbortController.ts
src/shim/object.ts
src/widget-core/Registry.ts
src/widget-core/meta/WebAnimation.ts
tests/core/unit/Evented.ts
tests/core/unit/QueuingEvented.ts
tests/i18n/unit/i18n.ts
tests/routing/unit/history/StateHistory.ts
tests/widget-core/unit/RegistryHandler.ts
tsconfig.esm.json
tsconfig.json

Provide updates for forwards compatibility with TypeScript from 2.6 to 3.0.
**Note:** This does not upgrade the TypeScript dependency, it is intended to enable consumers to use @dojo/framework on these TypeScript versions.
Related to #55

Forwards compatibility for TS2.7 through to TS3.0

---

src/widget-core/Registry.ts
src/widget-core/WidgetBase.ts
src/widget-core/d.ts
src/widget-core/interfaces.d.ts
src/widget-core/mixins/I18n.ts
src/widget-core/mixins/Themed.ts
src/widget-core/tsx.ts

Symbol usage causes issues as they are unique for a specific version, this change swaps references out for the using double underscore prefixed strings.

Remove symbol use in widget-core

---

src/widget-core/WidgetBase.ts
src/widget-core/d.ts
src/widget-core/interfaces.d.ts
tests/widget-core/unit/WidgetBase.ts
tests/widget-core/unit/d.ts

Supports lazy widgets directly in `w()` using a function that returns a Promise that resolves to a widget constructor.
```ts
class MyWidget extends WidgetBase {
private _loadWidget = () => {
return import('./lazy');
}
render() {
return w(this._loadWidget, {});
}
}
```
**Note:** The function cannot change across renders as it cannot be tracked.
Resolves #57

Support lazy widgets with a function that returns a promise in w()

---

src/widget-core/README.md
src/widget-core/decorators/watch.ts
tests/widget-core/unit/decorators/all.ts
tests/widget-core/unit/decorators/watch.ts

Adds a watch decorator that will call `invalidate` when the property is set automatically.
Resolves #74

Widget class property `watch` decorator

---

src/stores/process.ts

**Type:** bug
Fixes `createProcessFactoryWith` so that the returned factory correctly infer typings when used to create a process.
Resolves #80

Add generics for inferring types when using the process factory

---

package-lock.json
src/stores/state/Patch.ts
src/stores/state/compare.ts
tests/stores/unit/state/Patch.ts
tests/stores/unit/state/all.ts
tests/stores/unit/state/compare.ts

Adds helpful failure messages when a test operation fails. 

---

src/stores/README.md
src/stores/StoreInjector.ts
src/stores/StoreProvider.ts
src/stores/middleware/localStorage.ts
tests/stores/unit/StoreProvider.ts
tests/stores/unit/all.ts

Introduces `StoreProvider` to be used as any widget to inject the store into the vdom tree using a render property.
**Note:** This leaves the existing `StoreContainer` for backwards compatibility and graceful consumer upgrade, it will be removed in a future major release post v4.0.0. All references have been updated on the READM.md
See #76 for code snippets.
Resolves #76

StoreProvider for injecting store state into a widget tree

---

src/core/Destroyable.ts
src/core/Evented.ts

**Type:** bug
JSDoc changes.
Destroyable:
"destoryed" changed to new JSDoc.
Use "Handle" when talking about the type.
Use "Promise" when talking about the type.
Evented:
"is" to "if"

Minor JSDoc changes

---

src/routing/ActiveLink.ts
tests/routing/unit/ActiveLink.ts

**Type:** bug
Fix for `ActiveLink` not taking route parameters into account and falsely marking routes as active.
Resolves #72

Taking route parameters into account

---

src/shim/string.ts
src/shim/support/has.ts
tests/shim/unit/string.ts

**Type:** bug
A bug in the `es6-string-raw` check was causing it to always be false. When this flag is false, the shims for `endsWith`, `startsWith`, etc where always used.
Once this was fixed, the tests revealed some inconsistencies in how `endsWith` works natively and how our shim works.
Resolves #78

Fixing string shims

---

package.json
src/core/README.md
src/has/README.md
src/i18n/README.md
src/routing/README.md
src/shim/README.md
src/stores/README.md
src/testing/README.md
src/widget-core/README.md

**Type:** bug
Adds prettier for markdown and cleans up references

Clean up across the READMEs

---

.travis.yml
package.json

* Only runs linting during release and CI
* Fail CI if anything in the pipeline fails
Supercedes #35

Only run linting on release and CI; fail CI if any build steps fail

---

src/routing/Router.ts
src/routing/interfaces.d.ts
tests/routing/unit/Router.ts

**Type:** feature/bug
For routing the first match route specified in the configuration will be considered "the one", even if there is a more exact match in a later route within the configuration.
Assuming a routing configuration:
```ts
const config = [
{
path: 'foo',
outlet: 'foo-one'
},
{
path: 'foo',
outlet: 'foo-two',
children: [
{
path: 'baz',
outlet: 'baz'
}
]
},
{
path: '{bar}',
outlet: 'param'
},
{
path: 'bar',
outlet: 'bar'
}
];
```
Routing to `/bar`, should match against the `bar` outlet as it's more specific (a string literal match) but currently would match against the `param` outlet because it is registered first.
Routing to `/foo/baz` would currently match against the outlet, `foo-one` with a type of partial, rather …

Ensure to match against the most specific route

---

src/widget-core/vdom.ts

Adds a default export for `renderer` from vdom.

Add default export for renderer from vdom

---

src/routing/ActiveLink.ts
src/routing/Outlet.ts
src/routing/README.md
src/routing/Router.ts
src/routing/interfaces.d.ts
tests/routing/unit/Outlet.ts
tests/routing/unit/Router.ts

In order to evaluate routing at build time we need to ensure that it is static, these changes remove support for `onEnter` and `onExit` functions in the routing configuration. 
The same behaviour is supported by using the `outlet` event from the `router` instance:
```ts
router.on('outlet', ({ outlet, action }) => {
if (action === 'enter') {
if (outlet.id === 'my-outlet') {
// do something, perhaps fetch data or set state
}
}
});
```

Static routing configuration

---

src/widget-core/mixins/Projector.ts
tests/widget-core/unit/mixins/Projector.ts

**Type:** bug
The `Projector` mixin has been shimmed to ease the transition moving to the new vdom, however previously users could set properties and children after the projector had been appended. 
This wasn't possible with the existing implementation, so these changes add that capability to ensure that users who are setting properties and children on the projector after mounting will not break. This is not a common use case.

Support setting properties & children after appending in ProjectorMixin Shim

---

src/has/has.ts
src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

Adds warning when trying to add or remove nodes that are not distinguishable. The warning is behind the `dojo-debug` has flag.

Add key warning to vdom behind dojo-debug flag

---

package-lock.json
src/widget-core/WidgetBase.ts
src/widget-core/vdom.ts
tests/widget-core/unit/WidgetBase.ts
tests/widget-core/unit/decorators/diffProperty.ts
tests/widget-core/unit/vdom.ts

There shouldn't be any reason why a vnode cannot be returned in the render function passed to `vdom#renderer`.
```ts
const r = renderer(() => v('div', ['Hello, World!']));
r.mount();
```

Support returning VNodes from renderer function for vdom

---

src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

**Type:** bug
The typings for `processProperties` in `vdom` used an `any` but should have been typed correctly.

Correct the typings for processProperties in vdom

---

src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

**Type:** bug
Removes the shortcut of setting `className` directly for any DOM elements with all operations going through `classList.add`. 
Could have kept a shortcut using `domNode.setAttribute('class', 'myclasses');` but honestly would need to workout if that is actually worth it.
Resolves #104

Fix error when setting classes on SVG elements

---

src/widget-core/Registry.ts
src/widget-core/WidgetBase.ts
src/widget-core/d.ts
src/widget-core/interfaces.d.ts
tests/widget-core/unit/Registry.ts
tests/widget-core/unit/WidgetBase.ts

Adds support to use a "lazy define" directly in `w()`, that represents the label and registry item to be added to the widgets local registry.
Also resolves an issue with not peeling off the default module if the function returns an esm module.
Resolves #110 
Resolves #111

Increase support for defining registry items using w() by allowing a label to be defined

---

src/routing/ActiveLink.ts
tests/routing/unit/ActiveLink.ts

**Type:** bug
ActiveLink children should be rendered.
Resolves #109

Active link children bug

---

src/widget-core/WidgetBase.ts

**Type:** bug
`runAfterRenders` should be private.

Make runAfterRenders private

---

src/routing/Router.ts
tests/routing/unit/Router.ts

The delimiter for query params in the routing configuration was incorrect `$`, this fixes it to be `&`.
Resolves #114

Use '&' delimiter for query params

---

package-lock.json
src/widget-core/README.md
src/widget-core/d.ts
src/widget-core/interfaces.d.ts
src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

Adds a `onAttach` property to the `dom` pragma to enable users to specify an function to run after the node has been appended.
Resolves #121

Dom on append

---

src/has/README.md

Update the initial description of the has function to make its purpose more clear, especially with regards to features not added to the module prior to the use of has.
Resolves #99

Update has doc for clairty

---

src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

**Type:** bug
Ensure that widget's `onDetach` is called after the nodes have been removed.
Resolves #132

Call `onDetach` after the widget's nodes have been removed

---

src/routing/Router.ts
src/routing/RouterInjector.ts
tests/routing/unit/ActiveLink.ts
tests/routing/unit/Outlet.ts
tests/routing/unit/Router.ts
tests/routing/unit/RouterInjector.ts

**Type:** bug
Ensure that the routing events are emitted after the routing navigation is completed.
Resolves #136

Emit the routing event after the routing has been completed

---

README.md

Add migration section to readme

Update readme to have link to v4 migration guide

---

src/widget-core/README.md

Removing this line as no linting error is generated using the suggested configuration.
**Type:** bug
Remove a note from the README for widget-core regarding `tsx`. It states a linting error will occur as the import is unused, however no linting error appears. This was tested using [Creating widgets](https://dojo.io/tutorials/003_creating_widgets/) tutorial from [dojo.io](https://dojo.io). TSLint only flags the import as unused if no `jsx` can be found on the page.
Has `jsx`:
No `jsx`:
**Note**: That is typescript doing the checking there not tslint. But even tslint does not flag the `txs` import when `jsx` is present.

Remove linting error note for tsx

---

src/shim/Promise.ts
src/shim/main.ts
src/shim/support/has.ts
tests/shim/unit/Promise.ts
tests/shim/unit/support/has.ts
tests/widget-core/support/jsdom-plugin.ts

Adds `.finally()` method to Promise shim as defined in the [`Promise.prototype.finally` proposal](https://tc39.github.io/proposal-promise-finally/).
Resolves #45

Add .finally() to Promise shim

---

src/routing/Link.ts
src/routing/Router.ts
src/routing/history/HashHistory.ts
src/routing/history/StateHistory.ts
tests/routing/unit/Link.ts
tests/routing/unit/Router.ts
tests/routing/unit/history/StateHistory.ts

**Type:** bug
A collection of fixes for the routing:
* Support ctrl/cmd click
* Ensure links are generated with appropriate prefixes
* Ensure routing is synchronous with `setPath` when using `HashHistory`
* Strip leading `#` character when using `StateHistory`
Resolves #147 
Resolves #146 
Resolves #145

Fixes: Routing and Link Fixes

---

src/routing/ActiveLink.ts
tests/routing/unit/ActiveLink.ts

**Type:** bug
Active classes on `ActiveLink` should support `undefined` and `null` like all other classes (and the return interface of `this.theme()`
Resolves #149

Support undefined and null in active classes

---

src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

**Type:** bug
During an initial merge, remove nodes that could not be matched.

Remove nodes that could not be merged

---

src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

**Type:** bug
Fix to support setting a value on a `select` node. To set a value for a select the needs to have an option child with the value required. Adds a special `select-value` property to the select node and attempts to set the value when options are attached to the select parent. Only sets the value if the parent has a `select-value` property and the `select.value` doesn't equal the `select.select-value`
Resolves #153

Fix to support setting a value on a select node

---

src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

**Type:** bug
The select value doesn't set because the dom value has already been updated, this means that because we run `setValue` before setting the `select-value` property the mechanism resets the value to the previous select value.
Make sure we set the `select-value` on the select node before we try and set the actual value.

Bug: Value doesn't update when setting the value of select in UI

---

src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

**Type:** bug
Ensures that nodes that are conditionally rendered are inserted into the correct position in the DOM. This only affected conditional rendering from one node to two nodes.
Resolves #172

Ensure conditional nodes render in the correct order

---

package-lock.json
package.json

**Type:** bug 
Resolves #175
There is a vulnerability in the version of Diff being used, more details can be found at https://snyk.io/vuln/npm:diff:20180305
I updated this in the PR

Bug: update dependency diff to 3.5.0 to fix Regular Expression Denial of Service vulnerability

---

src/has/has.ts
src/routing/history/StateHistory.ts
tests/routing/unit/history/StateHistory.ts

**Type:** bug
A few fixes for `StateHistory` history adapter:
1) Add leading slash if missing to base path
1) Default to `window.__public_path__` if it exists
1) Strip base on pushing the state

fixes working with base paths in state history

---

src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

Registry items are resolved in `WidgetBase`, which means to enable using a registry item at the top level we need to wrap `w()` nodes (as well as `v()` nodes) with a wrapping widget.
The top level projector invalidation needs to ignore the wrapper, and pick the consumers widget.

Allow top level registry items in the renderer

---

src/widget-core/README.md
src/widget-core/mixins/Themed.ts
tests/widget-core/unit/mixins/Themed.ts

Adds `classes` property to `Themed`. If the `widgetKey` of the object matches a theme key associated with the widget via `@theme()`, applies extra class names when the classKey matches a class used by `this.theme()`.
```ts
interface Classes {
[widgetKey: string]: {
[classKey: string]: SupportedClassName[];
};
}
```
Resolves #163

Classes API for Themed Mixin

---

src/testing/README.md
src/testing/harness.ts
tests/testing/unit/harness.ts

We've already got the `select` utility, but this PR just exposes it to be a little more... friendly. Just adds a way to select DNodes directly from your harness. Once you have a DNode you can asset various things, call callbacks, etc.
```typescript
const h = harness(() => w(MyWidget, {
key: "root",
footer: v('button', { onclick: () => doSomething() }, 'footer')
}));
const [myWidget] = h.select("@root");
myWidget.properties.footer.onclick();
```
`select` will trigger a new render when you call it, so you can do things like,
```typescript
const foo = 'hello'
const h = harness(() => w(MyWidget, { foo }));
assert.isTrue(h.select('@span').length === 1);
foo = 'bar';
assert.isTrue(h.select('@span').length === 1);
```

Exposing select in harness

---

intern.json
package-lock.json
package.json
src/has/has.ts
src/shim/IntersectionObserver.ts
src/shim/ResizeObserver.ts
src/shim/WebAnimations.ts
src/shim/fetch.ts
src/shim/pointerEvents.ts
src/shim/util/amd.ts
src/widget-core/meta/Intersection.ts
src/widget-core/meta/Resize.ts
src/widget-core/meta/WebAnimation.ts
tests/shim/functional/amd.ts
tests/widget-core/unit/meta/Intersection.ts
tests/widget-core/unit/meta/Resize.ts
tests/widget-core/unit/meta/WebAnimation.ts

* Creates new shim modules for commonly used DOM ponyfills/polyfills in dojo/framework/shim.
* Adds new `build-elide` has pragma for all external polyfill imports that will be elided at build time
* Adds missing runtime `has` checks for all the new DOM APIs
* Use shims through dojo/framework
Related to #183

Include external polyfills in shim

---

src/widget-core/interfaces.d.ts
tests/widget-core/unit/vdom.ts

**Type:** bug
Adds the `SupportedClassName` interface for the `exitAnimation` and `enterAnimation` vnode properties. The `vdom` already deals with `undefined` and `null` values, added some tests to demonstrate that.
Resolves #134 (partially)
Supersedes #135

Update exit and enter animation to use SupportedClassName interface

---

src/testing/README.md
src/testing/harness.ts
tests/testing/unit/harness.ts

The `select` API was added to the `harness` to enable triggering a nested function on a widgets properties. However this was already possible using the `functionalSelector` on the `trigger` API.
As a side effect adding `select` exposed the ability to easily return sections of the widget tree and then be used instead of `expect` for specific assertions, which was never the intention of the API.

Remove select API from `harness`

---

src/has/has.ts
tests/has/unit/has.ts

* Removes `has` flags that are not used in `@dojo/framework`
* Removes support for async has flags.

Remove unused has flags and stop supporting async has flags

---

.travis.yml
package-lock.json
src/routing/history/StateHistory.ts
tests/routing/unit/history/StateHistory.ts

**Type:** bug
Do not set the `current` routing value in the constructor, only set after the on change event has fired and compared the `current` and `new` routes. This currently prevents the `defaultRoute` working as expected with the `StateHistory`
Resolves #195

FIX: state history default route

---

src/shim/ResizeObserver.ts

**Type:** bug
Add typings for `ResizeObserver`
Resolves #197

Add typings for resize observer shim

---

src/widget-core/WidgetBase.ts

**Type:** bug
Currently decorators are calculated for widgets the first time they are used in every new widget instance. The decorator map only needs to be calculated once per widget and cached for each subsequent new widget instance.
Resolves #185

Cache decorator map by widget

---

src/widget-core/decorators/watch.ts

**Type:** bug
Add default export for watch decorator.

Export default for watch decorator

---

src/widget-core/WidgetBase.ts
src/widget-core/interfaces.d.ts
src/widget-core/meta/Build.ts
tests/widget-core/unit/WidgetBase.ts
tests/widget-core/unit/meta/Build.ts
tests/widget-core/unit/meta/all.ts

A `Build` meta designed to be used to call node functions during build time render. The meta accepts a function and returns either `null` or the result of the function. If the function returns a promise then it will invalidate the widget and return the cached resolved value.
The results are cached, first by the function reference and then by the stringify'd arguments... The functions arguments must be serialisable so cannot accept functions or class instances etc.

Add Build Meta for Node BTR Functions

---

src/core/README.md
src/stores/README.md
src/stores/middleware/HistoryManager.ts
src/stores/middleware/localStorage.ts
src/stores/process.ts
src/testing/README.md
tests/stores/unit/middleware/HistoryManager.ts
tests/stores/unit/middleware/localStorage.ts
tests/stores/unit/process.ts

**Type:**feature
Adds the concept of "initializers" that can perform sync/async setup before a process is run. 
Resolves #90

Add before and after hooks to store middleware

---

package-lock.json
src/widget-core/meta/Build.ts
tests/widget-core/unit/meta/Build.ts

**Type:** bug
The response needs to be cached when returned synchronously to avoid returning `null` on subsequent calls.
Resolves #206

Cache build meta response when returned synchronously 

---

src/stores/StoreProvider.ts
tests/stores/unit/StoreProvider.ts

Ensure that the `StoreProvider` re-renders when it's parent is invalidated.
Resolves #188

always render the store provider

---

package-lock.json
src/stores/process.ts
tests/stores/unit/process.ts

When creating stores middleware, ideally consumers would use the `createCallbackDecorator` factory, with the breaking API change to support `before` and `after` middlewares we can leverage this factory to convert the old API to the new API enabling a seem less upgrade.
I wasn't sure if about adding a warn about using the old API, at the moment this is included behind the `dojo-debug` flag which will only execute in development builds. Open to suggestions 😄

Update createCallbackDecorator to convert old middleware API to new API

---

src/widget-core/registerCustomElement.ts
tests/widget-core/unit/registerCustomElement.ts

Use the root node of the widgets display property and set it on the custom element node. If none set default to `block` which is more common/preferable than the custom element default of `inline`
This solution differs to what I originally postured here: https://github.com/dojo/framework/issues/209#issuecomment-451537164, because I think this way is simpler, slightly more ergonomic and a lot of `dojo/widgets` already specify the desired `display` on their root node (for example: https://github.com/dojo/widgets/blob/master/src/theme/button.m.css#L5)
Resolves https://github.com/dojo/framework/issues/209
Thanks to @jcfranco for raising the original issue.

Use root node display property to set custom element root node display property

---

src/testing/README.md
src/testing/assertionTemplate.ts
tests/testing/unit/all.ts
tests/testing/unit/assertionTemplate.ts

Asserting full render functions can be brittle and end up encapsulating lots of logic in tests. While asserting only portions of a render function does not potentially cover everything (because a render function is the smallest unit).
To solve the above problems, Assertion Templates allow the user to always assert against a full render, while allowing them to easily modify the assertion themselves per scenario. 
The AssertionTemplate uses the existing selector api used elsewhere in harness, and supports an additional magic `~key` selector which is erased on render, this allows the user to select nodes in the AssertionTemplate, without the key being in the actual render result itself.
The api for …

Assertion Templates

---

src/widget-core/interfaces.d.ts

**Type:** bug
TypeScript 3.2.x starts throwing an error `RangeError: Maximum call stack size exceeded` due to circular type reference used as a default type.
This change updates the default type for the children nodes to `any` for a `DNode` to remove the use of `DNode` as a circular reference.
Resolves #205

Update type that causes 'Maximum call stack size exceeded' in 3.2.x

---

src/widget-core/README.md

Remove custom element initialization section from README

---

src/widget-core/meta/Block.ts
tests/widget-core/unit/meta/Block.ts
tests/widget-core/unit/meta/all.ts

Renames the `Build` meta to `Block`.

Rename Build meta to Block

---

src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

**Type:** bug
During a merge on the first render, use the next merge node candidate to insert before if the parent of the node about to be created and the next merge node have the same parent.
Resolves #228

Determine the correct insertion position when rendering extra nodes on a merge

---

src/shim/fetch.ts

Update to use the `build-elide` flag to determine whether to the fetch polyfill should be elided.

Only import `fetch` polyfill when `build-elide` is false

---

src/testing/README.md
src/testing/assertionTemplate.ts
tests/testing/unit/assertionTemplate.ts

Adds the ability prepend and append nodes when setting children. This is quite a common scenario which means the user has to get the children first and then spread currently. This is a non-breaking api change, the default behaviour is the same as currently, which is to replace.

Add `prepend` and `append` options to setChildren 

---

src/testing/README.md
src/testing/assertionTemplate.ts
tests/testing/unit/assertionTemplate.tsx

**Type:** bug
the tilde `~` is not supported as an attribute in `tsx`, so can't use the assertion key. This adds an also support attribute name of `assertion-key` so it can be used in tsx. note: you still select using the tilde `~`

Make sure we support assertion key for tsx in assertion templates

---

src/widget-core/meta/Block.ts
tests/widget-core/unit/meta/Block.ts

**Type:** bug
There is no need to cache value locally in the `Block` meta unless the `module` returns a promise. Only cache the resolved result from a promise, otherwise always use the result from the `module` (which is the from the block cache at runtime)

Block meta should only locally cache values resolved from promises

---

src/shim/ResizeObserver.ts

**Type:** bug
The shim returns `undefined` if using an AMD loader that uses the polyfill's UMD module since `default` is then `undefined`.
Resolves https://github.com/dojo/framework/issues/237#issuecomment-459818424

Add support for using resize-observer-polyfill's UMD module

---

src/testing/support/assertRender.ts
src/widget-core/WidgetBase.ts
src/widget-core/d.ts
src/widget-core/interfaces.d.ts
src/widget-core/mixins/Themed.ts
src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

Ternaries are often used to conditionally render nodes or apply classes. This change supports `false` for nodes and classes so that instead of a ternary, a logical `&&` expression can be used.
Current:
```ts
render() {
return v('div', { classes: [ applyClass ? 'my-class' : null ] }, [
showWidget ? w(MyWidget, {}) : null
]);
}
```
Can become:
```ts
render() {
return v('div', { classes: [ applyClass && 'my-class' ] }, [
showWidget && w(MyWidget, {})
]);
}
```
Whilst in this simple example it doesn't look much different, as widgets and classes because more complex, especially with when using `tsx` it can make a significant difference.

Support `false` type for classes and DNodes

---

src/testing/README.md
src/testing/assertionTemplate.ts
src/testing/harness.ts
src/testing/support/selector.ts
tests/testing/unit/assertionTemplate.tsx

Adds an insertChildren (before and after) to the assertion template. This allows adding nodes in places that `setChildren` doesn't easily allow.

Add insertChildren to assertion template

---

src/testing/assertionTemplate.ts
tests/testing/unit/assertionTemplate.tsx

**Type:** bug
The Assertion Template is meant to be immutable on setting, but currently only the first/base assertion is immutable.

Assertion Template should be immutable

---

src/i18n/README.md
src/testing/README.md
src/testing/assertionTemplate.ts
tests/testing/unit/assertionTemplate.tsx

Adds convenience methods (insertBefore, insertAfter, prepend, append and replace) to the Assertion Template api. This should make the api a little more discoverable over the third argument on `setChildren` and `insertChildren`, but functionally no different.
I've also renamed `insertChildren` to `insertSiblings` as the former was incorrect technically.

Add convenience methods for children setting in Assertion Templates

---

src/widget-core/interfaces.d.ts
src/widget-core/mixins/Themed.ts
src/widget-core/vdom.ts
tests/widget-core/unit/mixins/Themed.ts
tests/widget-core/unit/vdom.ts

**Type:** bug
The `false` returned for classes for the `SupportedClassName` type is expanded to `boolean` by TS in certain circumstances, which can cause errors when passing the result from `this.theme(` to `classes` on `VNodeProperties`. To deal with this we need to change the type to `boolean` and deal with `true` as a possible type (deal with in the same way as `false`, filter out).

Expand false type to boolean for supported class names

---

src/stores/state/Pointer.ts
tests/stores/unit/process.ts

**Type:** bug
Fixes a bug where using index keys for an object in stores that starts with a number.
Resolves #260

Support integer like index keys in stores

---

src/stores/state/Pointer.ts
tests/stores/unit/process.ts

**Type:** bug
Fixes a bug where using index keys for an object in stores that starts with a number.
Resolves #260

V5 - Support integer like index keys in stores

---

src/widget-core/meta/InputValidity.ts
tests/widget-core/unit/meta/InputValidity.ts
tests/widget-core/unit/meta/all.ts

This PR adds a new meta that specifically returns information from the browser's form validation API. This can be used to target HTML form elements, such as `<input type="email">`, and will return an object containing information about whether the element passes validation and whether it contains a message.
Given the following:
```tsx
render() {
const value = 'test';
const validity = this.meta(InputValidity).get('input', value);
render (
<input type="email" key="input" value={value}/>
)
}
```
This meta will return the following:
```typescript
{
valid: false,
message: "Please include an '@' in the email address. 'test' is missing an '@'."
}
```
Given the following:
```tsx
render() {
const value = …
```

add validation meta

---

src/widget-core/vdom.ts
tests/widget-core/support/util.ts
tests/widget-core/unit/vdom.ts

Deferred callbacks that impact the user, should be scheduled on the RAF over the RIC. Currently running detach on orphaned widgets, applying special VDom properties such as `focus` and executing deferred properties is done on the RIC. However as they are important for visual feedback these should be scheduled with a higher priority (therefore use the RAF).
Leaves the distinguishable node check on the RIC as it is acceptable to only run that when the browser is idle.

Prefer deferred render callback over idle callback for user impacting actions

---

src/stores/StoreProvider.ts
tests/stores/unit/StoreProvider.ts

Default the `stateKey` property to the default store registry label.
Resolves #261

Default `stateKey` property for `StoreProvider`

---

intern.json
package-lock.json
package.json
src/stores/README.md
src/stores/Store.ts
src/stores/state/ImmutableState.ts
tests/stores/unit/middleware/localStorage.ts
tests/stores/unit/process.ts
tests/stores/unit/state/ImmutableState.ts
tests/stores/unit/state/all.ts

Related to #48 
This creates a `MutableState` interface that has the properties of `State` as well as the `apply` function. It then breaks out the parts of store that implemented the `MutableState` interface into a default implementation, and allows an alternative implementation to be passed in to the constructor.
Includes an implementation using ImmutableJS. So far testing the performance impact of using ImmutableJS has not shown significant differences but I have not thoroughly tested it.

Factor out a `MutableState` interface from the store and provide an ImmutableJS implementation

---

src/widget-core/meta/Resize.ts
tests/widget-core/unit/meta/Resize.ts

**Type:** bug
Ensure that resize observers are disconnected when the meta is destroyed.
Resolves #270

Disconnect resize observer when meta is destroyed

---

src/stores/README.md

**Type:** bug
Fixes outdated documentation references to process callbacks

Fix references to middleware in stores documentation

---

README.md
src/i18n/README.md
src/widget-core/README.md

**Type:** bug
**Description:** Fix links to the localized i18n ref guide from elsewhere in framework.

Fix links to the i18n ref guide from elsewhere in framework

---

src/has/has.ts
src/shim/support/decorators.ts
tests/has/unit/has.ts

No longer throw when performing has() checks on unregistered features by default. Throwing by default is quite annoying, especially as we now leverage a lot of `has()` checks as part of the build tool where they are mostly progressive, so when using without the build tool (ie in a codesandbox) we'd have to write different code.
An additional strict param to enable the old functionality has been added.

No longer throw by default on unregistered has() checks 

---

src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

**Type:** bug
In scenarios where there are multiple nested widgets, the child `domNode` is not applied to the top level widget. This means that when there are two siblings that have nested widgets looking up the `domNode` for the insert before position does not work.
Additionally, when copying over the associated `domNode` to the new WNodeWrapper, check that it is still attached to the DOM when updating a widget, if the previous `domNode` is not attached to the DOM then do not copy over and let the attachment process execute to add the new `domNode`.
Resolves #296

Ensure that nodes are inserted in the correct position when nested within widgets

---

README.md
src/i18n/README.md
src/widget-core/README.md

**Type:** bug
**Description:** With the updated reference guide format, sans `index.md` file, links from elsewhere in the framework documentation should route to the general reference guide folder for the moment.
**Note** that there are also other minor formatting changes included in this PR as a result of prettier re-writing affected markdown files pre-commit.

Correct links to the i18n guide now there's no longer an index.md

---

src/widget-core/README.md
src/widget-core/mixins/I18n.ts
src/widget-core/mixins/Themed.ts
tests/widget-core/unit/d.ts
tests/widget-core/unit/tsxIntegration.tsx

**Type:** Enhancement
Removes interface extension of WidgetProperties in code and documentation.
Resolves #303

Stop extending WidgetProperties and remove documentation references

---

src/widget-core/WidgetBase.ts
src/widget-core/d.ts
src/widget-core/interfaces.d.ts
src/widget-core/registerCustomElement.ts
src/widget-core/vdom.ts
tests/routing/unit/Outlet.ts
tests/stores/unit/StoreProvider.ts
tests/widget-core/unit/Container.ts
tests/widget-core/unit/WidgetBase.ts
tests/widget-core/unit/decorators/beforeRender.ts
tests/widget-core/unit/decorators/inject.ts
tests/widget-core/unit/decorators/watch.ts

Changes to ensure that `VNode`s and `WNode`s created by users are not mutated by the rendering engine:
* Generate map of nodes to the widget instance that initially rendered to use for resolving registry items and adding DOM nodes to the widget NodeHandler for metas
* Remove `bind` from `VNode` and `WNode` and automatically bind Widget functions to the widget instance (excluding `constructor` and `render`)
* Resolve registry items in `vdom`, storing the resolved registry items on the `WNodeWrapper`
* Create text `VNode` and filter `undefined`, `null`, `false` and `true` items in `vdom`
* Remove `originalProperties` from `VNode` and `WNode`, process deferred properties in `vdom` storing the deferred properties …

Enhancement: Do not mutate VNodes or WNodes

---

src/testing/assertionTemplate.ts
src/testing/support/assertRender.ts
tests/testing/unit/assertionTemplate.tsx

Adds support for a new testing widget called `Mimic`. This can be used in Assertion Templates to explicitly ignore/match children against the actual render. This is extremely useful in scenario's with N number of items, as you can assert say the first one and mimic the remaining N items.
Adds `getProperties` and `setProperties` to complement the existing `getProperty` and `setProperties` api. The `setProperties` has one useful addition, if you pass it a function rather than an object, the function will be called with both the expected properties and the actual properties of that node. This allows you to emulate partial assertion on properties while still asserting the entire property set.

Assertion Template enhancements

---

src/shim/AbortController.ts

**Type:** bug
In app code you currently have to do this:
```
import AbortController, { AbortController as IAbortController } from '@dojo/framework/shim/AbortController';
// Later on...
let validateController: IAbortController;
// Later
let validateController = new AbortController();
```
I think this is because currently the `shim` doesn't export as the interface as we do with `ResizeObserver` and `IntersectionObserver`. 
Also the types are currently incorrect for `AbortSignal`s `onabort` method, they should be like so:
https://github.com/Microsoft/TypeScript/blob/master/src/lib/webworker.generated.d.ts#L499
This PR attempts to address these two things.
Happy to admit I'm not totally sure if this is the right solution so would be …

Adjustments to AbortController Polyfill

---

src/widget-core/decorators/customElement.ts
src/widget-core/registerCustomElement.ts
tests/widget-core/unit/decorators/customElement.ts

In preparation for https://github.com/dojo/webpack-contrib/issues/43 we need to make the `customElement` decorator stackable.  By default, everything that inherits `WidgetBase` will get a `@customElement` decorator with sensible defaults. So,
```ts
export interface MyProps {
prop: string;
}
class WorstWidgetEver extends WidgetBase<MyProps> { }
```
would become,
```ts
export interface MyProps {
prop: string;
}
@customElement({
tag: 'worst-widget-ever',
attributes: ['prop']
})
class WorstWidgetEver extends WidgetBase<MyProps> { }
```
To customize the declaration, you could add your own custom element decorator, which would look like this,
```ts
export interface MyProps {
prop: string;
}
@customElement({ …
```

Adding stackable customElement decorators

---

src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

**Type:** bug
Ensure that the latest vdom wrapper is used when processing detached nodes.
Resolves #310

Ensure that the latest wrapper is used when processing detached nodes

---

src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

Changes to support the ability for an application to pause hydrating the application when performing a merge against an existing DOM structure if the renderer hits a lazily loaded widget(s). 
This means that the VDOM will not "throw away" the existing DOM nodes while the lazy widget is loaded, instead will wait for the lazy widget to be loaded before continuing the merge operation.
Resolves #309

Pause initial render for lazy loaded widgets while performing a merge

---

src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

**Type:** bug
V5 back port of #310

V5 - Ensure that the latest wrapper is used when processing detached nodes

---

src/testing/assertionTemplate.ts
src/testing/harness.ts
tests/testing/unit/harness.ts
tests/testing/unit/harnessWithTsx.tsx

Instead of silently failing, throwing an error when a `h.trigger` encounters a selector that doesn't return any nodes.
Resolves #318

Throwing an error on missing selector in test harness trigger

---

src/routing/history/StateHistory.ts
tests/routing/unit/history/StateHistory.ts

**Type:** bug
I use `Link` widget to navigate, but If I click the same `Link` n times, I must click Back button n times to back to previous route. We should skip the same url.

We should skip the same URL

---

src/stores/process.ts
tests/stores/unit/process.ts

**Type:** bug
Re-jig the command factory typings to correct infer the type of the command created, either returning `promise<void>`, `promise<PatchOperation[]>`, `void` or `PatchOperation[]` not an union of them all.
Resolves #335

Fix typings for commands created by a command factory

---

src/stores/state/ImmutableState.ts
tests/stores/unit/state/ImmutableState.ts

**Type:** bug
Adds logic to convert Immutable List size to array length 
Resolves #343

Fix length return for immutable lists

---

src/stores/README.md
src/stores/process.ts
tests/stores/unit/process.ts

**Type:** bug
This fixes the issue where nested commands are run out of order when using the `state` proxy, by scoping the proxy to each inner command.
Resolves #340

Fix behavior for nested commands with state proxy

---

src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

**Type:** bug
Do not merge text nodes when the hydrated value is different to the existing text node's value.
Resolves #354

Do not use existing text node on merge when content is different

---

src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

Adds a replace algorithm to use when the previous nodes where all keyed and none of the keys are in the next nodes.
Resolves #351

Add optional replace algorithm based on previous and current nodes

---

src/widget-core/WidgetBase.ts
tests/widget-core/unit/vdom.ts

**Type:** bug
There is a problem with the new auto-bind code when there are multiple levels of inheritance. It currently only applies the binding logic to the first level of inheritance.
To fix this, we're walking the prototype chain up to `WidgetBase` and gathering all the properties from there. Since this is a bit of an expensive operation, we're also caching the result of the property gathering so it only needs to happen once per widget class.

Fixing a problem with auto-bind and multiple subclasses

---

src/core/WidgetBase.ts
src/core/vdom.ts
tests/core/unit/WidgetBase.ts
tests/core/unit/decorators/diffProperty.ts
tests/core/unit/vdom.ts

Moves the instance map to `vdom` from `WidgetBase` as `vdom` doesn't need to depend on `WidgetBase` at all anymore.

Move instance map to vdom

---

src/testing/harness.ts
tests/testing/unit/harness.ts
tests/testing/unit/support/assertRender.ts

**Type:** bug
The typings for the harness cause issues with widgets that have typed children.

Harness needs to support widgets with typed children

---

src/core/middleware/cache.ts
tests/core/unit/all.ts
tests/core/unit/middleware/all.ts
tests/core/unit/middleware/cache.ts

Adds a basic cache middleware for setting and getting values.
Resolves #366

Cache Middleware

---

src/core/vdom.ts
tests/core/unit/vdom.ts

A middleware that allows the rendering engine to control whether a widget is rendered using `pause` and `resume`. When performing a merge this pauses the rest of the vdom processing until the widget is set back to "resume" in order to ensure that the correct DOM nodes are matched and hydrated into the tree. In the non merge scenario the rest of the application is rendered, only skipping the widget that has been set to "pause".
```ts
import { create, defer, invalidator } from '@dojo/framework/core/vdom';
import { cache } from '@dojo/framework/core/middleware/cache';
const factory = create({ defer, cache });
const myExampleMiddleware = factory(({ middleware: { defer, cache, invalidator }}) => {
return { …
```

Defer Middleware

---

src/core/middleware/injector.ts
tests/core/unit/middleware/all.ts
tests/core/unit/middleware/injector.ts

Injector middleware that supports returning an injector from the registry and subscribing to the injectors invalidator event.
Resolves #369

Injector Middleware

---

src/core/middleware/cache.ts
src/core/middleware/icache.ts
tests/core/unit/middleware/all.ts
tests/core/unit/middleware/icache.ts

Built on top of the `cache` middleware, the `icache` middleware manages lazily value resolution and invalidation.
`getOrSet`: Gets an existing resolved value if it exists in the cache, otherwise sets the value passed.
`set`: Sets the value passed, if the value is a function it will be called and the returned result stored in the cache, or if the result is a promise then it will be added as pending and when the promise is resolved will update the value and invalidate.
`get`: Gets the value for the key or returns undefined if there is no entry or the result is pending.

Invalidating Cache Middleware

---

src/testing/assertionTemplate.ts
tests/testing/unit/assertionTemplate.tsx

Reports the missing selector in failed assertion template methods. Useful when debugging tests because it provides an indication of what part of the developer's code isn't working.
Resolves #353

report not found selectors in assertion template methods

---

src/core/middleware/block.ts
tests/core/unit/middleware/all.ts
tests/core/unit/middleware/block.ts

Middleware to be used with Dojo blocks, as per the existing meta runs blocks and caches the results for unique calls.
Resolves #370

Block Middleware

---

src/core/meta/Intersection.ts
src/core/middleware/intersection.ts
tests/core/support/jsdom-plugin.ts
tests/core/unit/middleware/all.ts
tests/core/unit/middleware/intersection.ts

Middleware that leverages Intersection Observers to determine if a node with a given key is intersecting with the view port or with a specified root node.
Resolves #374

Intersection Middleware

---

src/shim/Map.ts
src/shim/README.md
src/shim/Set.ts
src/shim/WeakMap.ts
src/shim/array.ts
src/shim/math.ts
src/shim/object.ts
src/shim/string.ts
tests/shim/unit/array.ts
tests/shim/unit/math.ts
tests/shim/unit/object.ts
tests/shim/unit/string.ts

Conversion of shims that are used directly to polyfills, while maintaining backwards compatibility with current usage. Also makes sure that we are actually applying our more standard polyfills to the global object when appropriate, as some modules were not. This is one part of the work for #279.

Make shims polyfills

---

src/core/middleware/resize.ts
src/core/vdom.ts
tests/core/unit/middleware/all.ts
tests/core/unit/middleware/resize.ts

Middleware using ResizeObservers, invalidates when a node resizes and returns the ContentRect dimensions.
Resolves #383

Resize Middleware

---

src/core/middleware/injector.ts
tests/core/unit/middleware/injector.ts

**Type:** bug
For the injector middleware the subscription handles need to be destroy when the widget is destroyed and also allow the consumer to destroy them with a handle.

Destroy Injector Subscribe Handles

---

src/core/vdom.ts
tests/core/unit/vdom.ts

Change `diffProperties` to `diffProperty` and require each call to pass the property name that will be diff'd. Properties with a registered custom diff will be excluded from the default diff.
Related to #367

Change diff properties middleware to work with singular properties

---

src/core/RegistryHandler.ts
src/core/diff.ts
src/core/middleware/theme.ts
src/core/mixins/Themed.ts
src/core/vdom.ts
tests/core/unit/diff.ts
tests/core/unit/middleware/all.ts
tests/core/unit/middleware/theme.ts
tests/core/unit/mixins/Themed.ts

Theme middleware to work to determine the correct classes based on the current theme & set themes.
Resolves #371

Theme Middleware

---

src/core/middleware/i18n.ts
src/core/mixins/I18n.ts
tests/core/unit/middleware/all.ts
tests/core/unit/middleware/i18n.ts
tests/core/unit/mixins/I18n.ts

An i18n middleware that returns localised messages and formatters. Provides an API to get and set the locale details (`locale` and `rtl`).
**Note:** Does not automatically decorate the top node of a widget with `rtl` and `locale` properties as the current mixin does.
Resolves #372

I18n Middleware

---

src/core/middleware/focus.ts
tests/core/unit/middleware/all.ts
tests/core/unit/middleware/focus.ts

Focus middleware builds on the primitive focus functionality provided by vdom and enables management of focus across widget boundaries.
The focus middleware provides a function called `shouldFocus` that manages when a widget or their child widgets can apply focus, `shouldFocus` will only return true the first time it is called until focus is called again on the widget.
Resolves #400

Focus Middleware

---

src/core/middleware/store.ts
tests/core/unit/middleware/all.ts
tests/core/unit/middleware/store.ts

Dojo stores middleware
Resolves #397

Store Middleware

---

src/core/has.ts
src/shim/Map.ts
src/shim/Observable.ts
src/shim/Promise.ts
src/shim/Set.ts
src/shim/WeakMap.ts
src/shim/array.ts
src/shim/iterator.ts
src/stores/process.ts

**Type:** bug
Add has flags to ensure that shims are elided correctly.

Ensure shims are elided correctly

---

src/core/vdom.ts
tests/core/unit/vdom.ts

**Type:** bug
Ensure functional widgets are invalidated when they have or had children.
Related to #352

Invalidate if there are new or old children

---

src/core/vdom.ts
tests/core/unit/vdom.ts

**Type:** bug
When setting the owning node, do not break on `undefined`, `null` or `false` nodes as these are valid.

Do not break on undefined/false/null nodes

---

src/stores/process.ts
tests/stores/unit/process.ts

Providing the process `id` to `before` callbacks in process middleware.
Resolves #308

Providing process ID to all middleware callbacks

---

src/routing/ActiveLink.ts
src/routing/Link.ts
src/routing/Outlet.ts
tests/routing/unit/ActiveLink.ts
tests/routing/unit/Link.ts
tests/routing/unit/Outlet.ts

Converts the existing `Link`, `ActiveLink` and `Outlet` class widgets to function widgets leveraging middleware.
Related to #352

Convert routing widgets to functional widgets and use middleware

---

src/testing/README.md
src/testing/assertionTemplate.ts
tests/testing/unit/assertionTemplate.tsx

Extends the API for `AssertionTemplate` methods that work with children to support a function. This is the recommended way to work with these APIs to avoid issues with mutability.
Adds warning that the `DNode[]` API has been deprecated in favour of using a function `() => DNode[]`.
Warning: 
```
The array API (`children: DNode[]`) has been deprecated. Working with children should use a factory to avoid issues with mutation.
```
Resolves #333

Support factory functions for children replace on assertion templates

---

src/routing/Outlet.ts

**Type:** bug
Default export for `Outlet`.

Default export for `Outlet`

---

src/stores/process.ts
tests/stores/unit/process.ts

**Type:** bug
Any object and array values returned when accessing the state object are also proxies, in order to handle nested updates. When one of these values is set back on the state object there is a check to get the object value instead of the proxy. However in the case of `filter`, and any number of other possible scenarios, the object that is being set is not a proxy and is not known by the proxy, but contains proxies. This resulted in proxies being set as properties on the state which leads to an infinite regress.
To fix this the proxy removal check is now recursive. 
todo-mvc with fix:
https://dev-kxynqtvhqn.now.sh/
Fork:
https://github.com/maier49/todomvc/tree/fixed
Resolves #404

Fix store `state` interface call stack error

---

src/core/animations/cssTransitions.ts
src/core/interfaces.d.ts
src/core/vdom.ts
tests/core/unit/vdom.ts

Do not automatically apply an animations transition strategy. If `enter` or `exit` transitions are used for an application a strategy will need to be passed on application mount.

Do not automatically import css transition strategy for vdom

---

src/core/interfaces.d.ts
src/core/vdom.ts

**Type:** bug
Default the middleware type to ensure that property inference works for middleware and widgets.
Supersedes #419

Fix property inference for middleware

---

src/core/registerCustomElement.ts
tests/core/unit/registerCustomElement.ts

**Type:** bug
It's evidently not guaranteed that a custom element's children will be available when it is connected ([see discussion here](https://github.com/w3c/webcomponents/issues/551)), but our `connectedCallback` was setup as if it was. I've setup a mutation observer so that the element will wait till the document is loaded  or an element after it in the HTML hierarchy is present to perform setup logic. 
Resolves #342

Fix custom element initialization

---

src/core/NodeHandler.ts
src/core/WidgetBase.ts
src/core/vdom.ts
tests/core/unit/NodeHandler.ts
tests/core/unit/vdom.ts

Clearing the node handler after the widget render no longer works as deferred properties are now resolved in vdom. There is no need to clear the entire node map, we can just remove the nodes from the map when the dom node is removed.

Remove node from handler when DOM node is removed

---

src/core/vdom.ts
src/routing/Outlet.ts

**Type:** bug
From realworld testing some small issue have been identified and resolved:
* Do not add a widget on the invalidation queue when the invalidate occurs whilst "rendering"
* Do not run deferred properties if the owning widget has been destroyed
* Revert change for `Outlet` that moved `invalidate` inside the property diff condition, since it always needs to re-render from the parent.

Do not queue an invalidation when an invalidate occurs during a render

---

src/core/vdom.ts
tests/core/unit/vdom.ts

Adds support for virtual nodes in the rendering engine. This enables nicely returning arrays when using TSX.
```tsx
render() {
return (
<virtual><div/><div/></virtual>
);
}
```
Resolves #424

Virtual Node Support

---

src/shim/array.ts

`MAX_SAFE_INTEGER` is used by array which means that all of `number.ts` is included in application bundles. Duplicating and inlining one variable to ensure that superfluous code isn't included in built application is a good deal.

Inline MAX_SAFE_INTEGER value so number is included in every app build

---

src/core/vdom.ts

**Type:** bug
Always set rendering back to false even if the widget is not dirty.

Always set rendering back to false

---

src/core/vdom.ts
tests/core/unit/vdom.ts

Warn for functional widgets that are being added and removed from child lists without keys

Warn for functional widgets when children are not distinguishable

---

src/testing/mocks/middleware/store.ts
tests/testing/unit/mocks/middleware/all.ts
tests/testing/unit/mocks/middleware/store.tsx

A mock store middleware testing widgets that use the `store` middleware. Automatically injects an empty store for testing, providing an API for running operations against the store.
```tsx
// Widget
import { create, tsx } from '@dojo/framework/core/vdom'
import createStoreMiddleware from '@dojo/framework/core/middleware/store';
import { myProcess } from './processes';
import MyState from './interfaces';
// application store middleware typed with the state interface
// Example: `const store = createStoreMiddleware<MyState>();`
import store from './store';
const factory = create({ store }).properties<{ id: string }>();
export default factory(function MyWidget({ properties: { id }, middleware: store }) {
const { …
```

Mock Store Middleware

---

src/core/middleware/breakpoint.ts
tests/core/unit/middleware/all.ts
tests/core/unit/middleware/breakpoint.ts

Breakpoint meta that returns the matching breakpoint based on the width of a node. Provides a factory that can be used to create breakpoint meta with a custom set of breakpoints that can be used throughout an application. By default the breakpoint meta uses:
```ts
{
SM: 0,
MD: 576,
LG: 768,
XL: 960 
}
```
The breakpoints can also be overridden when using the `.get` 
```ts
breakpoint.get('root', { 'custom-small': 100, 'custom-large': 700 }
```

Breakpoint middleware

---

src/core/vdom.ts
tests/core/unit/vdom.ts

**Type:** bug
Fixes the logic for node ordering when using a "virtual" node.
Resolves #438

Fix the order logic dealing with node insertion when using a virtual node

---

src/core/vdom.ts
tests/core/unit/vdom.ts

**Type:** bug
SVG elements can have a lowercase `tagName` which meant they were never matched when processing merge nodes. This changes to upper case both tags before comparison.
Includes a change to move the orphaned node clean up to after the dom instructions are completed, as the failing unit test for the SVG failed first as it tried to insert before a node that has already been removed from the DOM.

Ensure that SVG nodes can be merged

---

src/core/middleware/block.ts
tests/core/unit/middleware/block.ts

Changes the API for `block` from `block.run(myBlock)()` to `block(myBlock)()` and fixes the typings for inferring the block function parameters.

Fix block function argument typings and update API

---

docs/en/testing/basic-usage.md
docs/en/testing/introduction.md
docs/en/testing/supplemental.md

Update the testing reference guide with new APIs and features for supporting mock middleware.

Update testing reference guide

---

docs/en/styling-and-theming/basic-usage.md
docs/en/styling-and-theming/supplemental.md

Updates for the theming reference guide to include the theme middleware and functional widgets.

Update to theme reference guide

---

src/core/vdom.ts
tests/core/unit/vdom.ts

Adds support for a special `vnode` tag, `body` that will render its children directly to the `document.body`.
```tsx
import { create, tsx } from '@dojo/framework/core/vdom';
const factory = create();
const MyWidget = factory(function MyWidget() {
return (
<div>
<body><div>Body Node</div></body>
<div>Normal Node</div>
</div>
);
});
```
Resolves #447

Support rendering nodes to the document body

---

docs/en/testing/supplemental.md
src/core/interfaces.d.ts
src/core/middleware/i18n.ts
src/core/middleware/theme.ts
src/core/vdom.ts
src/routing/ActiveLink.ts
src/routing/Link.ts
src/routing/Outlet.ts
src/testing/harness.ts
tests/core/unit/middleware/block.ts
tests/core/unit/middleware/breakpoint.ts
tests/core/unit/middleware/cache.ts
tests/core/unit/middleware/dimensions.ts
tests/core/unit/middleware/focus.ts
tests/core/unit/middleware/i18n.ts
tests/core/unit/middleware/icache.ts
tests/core/unit/middleware/injector.ts
tests/core/unit/middleware/intersection.ts
tests/core/unit/middleware/resize.ts
tests/core/unit/middleware/store.ts
tests/core/unit/middleware/theme.ts
tests/core/unit/vdom.ts
tests/testing/unit/harness.tsx

The `properties` and `children` are injected one time into both middleware and widgets. With middleware it is easy to destructure the properties outside of the middleware API meaning that when it is used in subsequent renders it will be the stale properties from the first render.
This changes the `properties` and `children` to be functions which is clearer to users that it needs to be called on demand to get the latest properties/children.
Related to #349

Change `properties` and `children` API to functions

---

src/core/vdom.ts
tests/core/unit/vdom.ts

Change how children and parents are referenced by other wrappers, preferring using the wrapper id over storing the wrapper object itself. This should reduce the references that are held in memory and help the memory footprint generally.

Prefer wrapper ids over references for tracking nodes

---

docs/en/i18n/basic-usage.md
docs/en/i18n/supplemental.md

Updates the `18n` docs to use function-based widgets and middleware first.

Update i18n docs to reflect function-based widgets and middleware

---

src/core/vdom.ts
tests/core/unit/vdom.ts

**Type:** bug
Move the replacement of text nodes to the DOM application queue.

Should not affect DOM outside processing DOM instructions

---

src/core/vdom.ts
tests/core/unit/vdom.ts

**Type:** bug
Ensure nodes created by a widget are removed when wrapped in a body.
Resolves #462

Ensure that widgets are removed from the body when they are detached

---

src/stores/README.md

This is just a simple typo fix in the stores README.

Fix createProcessFactoryWith name in stores README

---

src/core/decorators/customElement.ts
src/core/registerCustomElement.ts
tests/core/unit/decorators/customElement.ts
tests/core/unit/registerCustomElement.ts

@mwistrand Updated framework to work with descriptors on the class/function instead of the prototype to go along with the changes in dojo/webpack-contrib#185

Add custom element descriptor directly to widget

---

src/core/has.ts
src/shim/global.ts
src/shim/globalThis.ts
tests/shim/unit/all.ts
tests/shim/unit/globalThis.ts

Modifies `global.ts` to defer to `globalThis`, and adds a has check and shim for it.
Related to #222

Defer to, and provide a shim for, globalThis

---

src/core/middleware/icache.ts

Improve argument and return typing on `icache` middleware's getOrSet method.
This is completely a typing change with no implementation changes.
**Before**:
```tsx
icache.getOrSet('test', 'test'); /* Type: any */
icache.getOrSet('test', () => 'test'); /* Type: any */
icache.getOrSet('test', () => Promise.resolve()); /* Type: any */
icache.getOrSet<string>('test', 'test'); /* Type: string | undefined */
icache.getOrSet<string>('test', 42); /* No Error, Type: string | undefined */
icache.getOrSet<string>('test', () => 'test'); /* Type: string | undefined */
icache.getOrSet<string>('test', () => Promise.resolve()); /* Type: string | undefined */
```
**After**:
```tsx
icache.getOrSet('test', 'test'); /* Type: 'test' …
```

Improve return typing on icache getOrSet

---

src/testing/mocks/middleware/breakpoint.ts
tests/testing/unit/mocks/middleware/all.ts
tests/testing/unit/mocks/middleware/breakpoint.tsx

Adds a mock for the breakpoint middleware
Resolves #468

Add breakpoint middleware mock

---

src/shim/global.ts

**Type:** bug
Checking for `globalThis` this was breaking testing functionality that expected the jsdom window to be returned from `global.ts`. This adds an explicit check that should detect when the window has been provided by jsdom.

Add jsdom user agent check to global shim

---

docs/en/stores/basic-usage.md
docs/en/stores/introduction.md
docs/en/stores/supplemental.md

This is a copy of https://github.com/dojo/framework/pull/341 but that has been updated to address the requested feedback.
If this is merged, we can close https://github.com/dojo/framework/pull/341.

Stores reference

---

docs/en/routing/introduction.md
docs/en/routing/supplemental.md

Added an example to the introduction page that shows what the URL path looks like when using routing and points to the History Manager section of the supplemental material to get more information. This PR also expands on the documentation for the `MatchDetails` object to provide more clarity on how different scenarios affect the values of its members.

Update routing guide

---

src/testing/assertionTemplate.ts
tests/testing/unit/assertionTemplate.tsx

**Type:** bug
Allows insert, remove, and replace operations on nodes in a root array of an assertion template.
Resolves #434

support assertionTemplate operations on array root

---

docs/en/outline/introduction.md
docs/en/outline/supplemental.md

**Type:** documentation
- Adds the reference content outline to `framework` rather than `site` - it's best placed alongside the other guides for consistency (especially links) & ease of translation
Closes dojo/site#128

Added reference content outline guide

---

docs/en/testing/introduction.md
docs/en/testing/supplemental.md

Updated introductory and supplemental testing guides to use functional widgets and reflect v6 module paths.

Update testing docs to use functional widgets

---

src/routing/history/StateHistory.ts
tests/routing/unit/history/StateHistory.ts

Changes the `StateHistory` module to generate relative links, deprecates the `base` option as this is automatically detected by the `base` property in the `.dojorc` when using the dojo build pipeline.
Outside of the dojo build pipeline, the has flag `app-base` would need to be configured manually and base HTML element added to the index.html, e.g. `<base href="[the app base]" />.
Will warn when trying to use the `base` history option in development mode.

Update StateHistory to generate relative links and use the `app-base` has flag

---

src/core/middleware/icache.ts

**Type:** bug
Fix the `getOrSet` typings for a `promise` factory to return `undefined | T`, with T being the return type of the promise or the generic passed to `getOrSet`.
**Before:**
```ts
/* Type: undefined */
icache.getOrSet<string>('test', () => Promise.resolve());
/* Type: undefined */
icache.getOrSet<string>('test', () => new Promise<string>(() => {}));
/* Type: undefined */
icache.getOrSet('test', () => new Promise<string>(() => {}));
```
**After:**
```ts
/* Type: string | undefined */
icache.getOrSet<string>('test', () => Promise.resolve());
/* Type: string | undefined */
icache.getOrSet<string>('test', () => new Promise<string>(() => {}));
/* Type: string | undefined */
icache.getOrSet('test', () => new …
```

Fix return type for getOrSet for a promise factory

---

tests/testing/unit/assertionTemplate.tsx

Improves the replace assertionTest for non-root nodes and moves it next to the other replace test.
Related to #470 [(comment)](https://github.com/dojo/framework/pull/470#discussion_r312182340)

add regular replace test

---

src/core/decorators/customElement.ts
src/core/registerCustomElement.ts
tests/core/unit/registerCustomElement.ts

Getting rid of `childType` for custom elements and detecting it automatically. Previously, a user would have to manually specify the childType (NODE, TEXT, or DOJO) that a custom element would contain. Now, if there are any widget nodes, the child list includes DOM nodes and dojo widgets, but not text nodes. If there are no widget nodes, the child list includes text nodes and DOM nodes.
**Note: This is a breaking change from the current behavior!**
Resolves #304

Autodetecting custom element child type

---

src/core/interfaces.d.ts
src/core/vdom.ts
tests/core/unit/vdom.ts

Adds support to `v()` so that the `target` on the `event` argument of event handers, such as `onclick` etc are correct typed to the appropriate DOM element type based on the tag.
Resolves #496

Infer target type for vnode event handlers

---

src/core/registerCustomElement.ts
tests/core/unit/registerCustomElement.ts

Currently there is no way to deal with "reserved" property names when working with custom elements. This change introduces a new API `.set(key, value)` for reserved properties.
Currently only `focus` is included in as a reserved property that can be expanded on in the future.
Resolves #498

Deal with reserved property names

---

src/core/decorators/customElement.ts
src/core/registerCustomElement.ts
src/core/vdom.ts
tests/core/unit/registerCustomElement.ts

The previous attempt to auto detect childType only worked when the CE javascript was loaded before the element was created. If the CE javascript was loaded after the custom element is created then it caused issues with hydration (as dojo didn't know what was a Dojo CE and what wasn't).
The current behaviour only supports a single specified child type per widget and this auto detection mirrors that. It is assumed that if there are any children with a `-` character that the childType is `DOJO` otherwise it's `NODE/TEXT`. 
If a widget is specifically for non Dojo CE children then the existing configuration can be used.
**Note:** Additionally empty text nodes are filtered out from the childNodes
Supersedes #494 …

Auto detect custom element child type

---

docs/V6-Migration-Guide.md

Update to the v6 migration guide.

Update v6 migration guide

---

docs/en/stores/introduction.md

**Type:** doc typo
There is a small typo in the store doc
`import { registerStoreInjector } from '@dojo/framework/store/StoreInjector';`
should be
`import { registerStoreInjector } from '@dojo/framework/stores/StoreInjector';`
Got me in a quick copy/paste walkthrough

doc: fix path typo in store doc

---

src/routing/Router.ts
tests/routing/unit/Router.ts

**Type:** bug
The logic for autostart is incorrect which causes registering multiple history managers when it is set to `autoStart: false`.

Always autostarts due to incorrect logic

---

src/core/WidgetBase.ts
tests/core/unit/vdom.ts

**Type:** bug
Skip autobind for getter propertoes on class-based widgets.
Resolves #521

Skip autobind for getters on class-based widgets

---

src/core/vdom.ts
tests/core/unit/vdom.ts

**Type:** bug
The destroy middleware is useful for ensuring widgets can deal with any references when they are removed from the tree. However currently, destroy is called in the order that the middleware dependencies of a widget call destroy. This is generally top down as `destroy` is usually called at the point of a middlewares initialisation, but this is not a guarantee meaning that not only is it generally called in the wrong order but also is not deterministic.
This change records the dependency order of all middleware for a widget and when there have been destroy functions registered ensures that they called in the right order from the deepest to shallowest (first in, last out).
Resolves #518

Ensure middleware gets destroyed from deepest to shallowest

---

docs/en/testing/supplemental.md
src/testing/mocks/middleware/icache.ts
tests/testing/unit/mocks/middleware/all.ts
tests/testing/unit/mocks/middleware/icache.tsx

Introduces an icache middleware mock as well as documentation for using it and creating custom middleware mocks.
Resolves #519

Middleware mocking documentation

---

src/routing/ActiveLink.ts
src/routing/README.md
tests/routing/unit/ActiveLink.ts

Adds an `isExact` option to the `ActiveLink` properties that if true will only add active classes if the matched outlet's `isExact` function returns `true`.
Resolves #492

Add 'isExact' option to active link

---

src/core/WidgetBase.ts
tests/shim/unit/math.ts

**Type:** bug
Ensure that initial properties is set to false.
Resolves #538

Ensure that initial properties are set to false

---

src/core/WidgetBase.ts
src/core/interfaces.d.ts
src/core/vdom.ts
tests/core/unit/tsx.ts
tests/core/unit/tsxIntegration.tsx

**Type:** bug
Fix types for children when using class-based widgets and tsx. Provides parity to the exiting children typing support which is typed to `DNode | DNode[]`.
Related to #528

Fix children types with tsx and class-based widgets

---

src/core/mixins/Focus.ts
src/core/mixins/Themed.ts

**Type:** bug
Add JsDoc for property interfaces.

Add some missing jsdoc for property interfaces

---

src/core/interfaces.d.ts
src/core/middleware/i18n.ts
src/core/middleware/theme.ts
src/core/mixins/I18n.ts
src/core/mixins/Themed.ts

**Type:** bug
The `theme` and `i18n` middlewares are currently coupled to their equivalent mixin. This is strange for users as they would need to import interfaces from a mixin when using a middleware and also result in the mixin and it's dependencies being included in an application bundle.

Decouple Theme and I18n Middleware and Mixins

---

src/core/vdom.ts
tests/core/unit/vdom.ts
tests/shim/support/has-plugin.ts

**Type:** bug
Using `typeof` allows using `__DOJO_SCOPE` without dojo build tooling, instead of throwing error `VM69:2 Uncaught ReferenceError: __DOJO_SCOPE is not defined`

Use typeof to support vdom module being loaded without build tooling

---

src/core/interfaces.d.ts

**Type:** bug
TSX supports a mix of `DNode` and `DNode[]` which needs to be included in the default typing. Also the children of `WNode` should be `DNode[]`, this was mistakenly changed to `any[]` with the initial children typing PR.

Missing edge case for children typing

---

src/core/vdom.ts
tests/core/unit/vdom.tsx

**Type:** bug
Ensure the rendering flag is set correctly based on the _renderScheduled flag.

Ensure the rendering flag is reset correctly

---

docs/zh-CN/building/introduction.md
docs/zh-CN/building/supplemental.md
docs/zh-CN/creating-widgets/introduction.md
docs/zh-CN/creating-widgets/supplemental.md
docs/zh-CN/middleware/introduction.md
docs/zh-CN/middleware/supplemental.md
docs/zh-CN/outline/introduction.md
docs/zh-CN/outline/supplemental.md
docs/zh-CN/stores/introduction.md
docs/zh-CN/testing/supplemental.md

A couple of back ports for the translated doc content.

Backport Simplified Chinese Content

---

src/core/vdom.ts
tests/core/unit/vdom.tsx

**Type:** bug
`diffProperty` callbacks are not called for the first render which could mean that logic the user requires to run _every_ render. This changes ensures that the diff properties are executed immediately when registered, subsequently they will be executed as they are currently.

Ensure that diff property call backs are called immediately when registered

---

src/core/vdom.ts
tests/core/unit/vdom.ts

**Type:** bug
Backport of #572 
* failing unit test for diff property on the first render
* Call diff properties immediately when they are registered
* prettier

Ensure that diff property call backs are called immediately when registered (#572)

---

src/core/middleware/focus.ts
tests/core/unit/middleware/focus.ts

**Type:** bug 
The state in the focus middleware was incorrectly getting the current value from the cache, but setting it in the icache. This means that after the first focus call, `shouldFocus` would always be `false`. This highlights just one of the issues with mixing icache and cache.
This changes the logic to use icache for everything except the active element which is simply kept in the scope of the middlware.

Fix state in focus middleware

---

docs/zh-CN/middleware/supplemental.md
docs/zh-CN/outline/introduction.md
docs/zh-CN/outline/supplemental.md

Change inter-docs links for building docs.

update zh-CN building doc links

---

src/core/vdom.ts
tests/core/unit/vdom.tsx

**Type:** bug
Back port of #564 
* support tsx in vdom tests
* failing unit test for live property binding
* fix up failing unit tests
* support live binding to children and properties
* abstract widget args to function
* use factory for middleware

Provide live binding for properties and children with function-based widgets (#564)

---

src/core/middleware/focus.ts
tests/core/unit/middleware/focus.ts

**Type:** bug
Back port of #575 
* failing unit test
* do not mix cache and icache

Fix state in focus middleware (#575)

---

src/core/vdom.ts
tests/core/unit/vdom.tsx

**Type:** bug
Check if the node is contained in the body if it isn't contained in the mount node.

Check body for attached nodes

---

src/core/middleware/focus.ts
tests/core/unit/middleware/focus.ts

**Type:** bug
When calling `shouldFocus` it should not cause an invalidation of the widget which it currently does. As the function can be called outside of the widgets render method it can cause render looping issues.

Bug: Fix calling invalidate when checking is a widget or node should focus

---

package-lock.json
src/testing/assertionTemplate.ts
tests/testing/unit/assertionTemplate.tsx

**Type:** bug
Ensure that children set on assertion templates are always immutable.
Resolves #586

Ensure assertion template children are immutable

---

package-lock.json
src/i18n/i18n.ts
tests/i18n/unit/i18n.ts

**Type:** bug
When resolving the best-fit locale for registering or reading message bundles, ensure the most-specific locale that is supported by the message bundle is used to both register the message bundle with the i18n ecosystem and read bundle data when formatting messages .For example, if a bundle supports the "zn" locale, but "zn-CH" is passed to both `@dojo/framework/i18n/i18n.default` and `@dojo/framework/i18n/i18n.getMessageFormatter`, then the most-specific supported locale (in this case, "zh") should be used when writing to or reading from the internal cache, respectively.
This fixes a bug that causes `E_MISSING_MESSAGE_BUNDLE` errors to be thrown when a generic locale is registered/read before a more-specific …

Fix: i18n supported locale resolution

---

src/core/WidgetBase.ts
src/core/interfaces.d.ts
tests/core/unit/vdom.tsx

**Type:** bug
Fix property interference when using a widget with mixins via tsx.
Resolves #592

Ensure mixins properties are inferred when using tsx

---

src/testing/harness.ts
tests/testing/unit/harness.tsx

Runs compares for actual result on each call to `expect`
Resolves #600

Run comparators when using expect with an actual render argument

---

docs/en/middleware/supplemental.md
src/core/middleware/cache.ts
src/core/middleware/icache.ts
tests/core/unit/middleware/cache.ts
tests/core/unit/middleware/icache.ts

Two new APIs for dealing with cache eviction from the `icache`.
```ts
console.log(icache.getOrSet('key', 'foo')); // logs `foo`
if (icache.has('key')) {
icache.delete('key');
}
console.log(icache.getOrSet('key', 'bar')); // logs `bar`
```
Resolves #604

Enable cache eviction with icache

---

src/core/middleware/icache.ts
tests/core/unit/middleware/icache.ts

**Type:** bug
Ensure the typings are correct for `icache.set` when working with functions or promise factories.
Resolves #606

Fix typed icache set interface

---

docs/en/middleware/supplemental.md
docs/zh-CN/middleware/supplemental.md
src/core/middleware/block.ts
src/core/middleware/cache.ts
src/core/middleware/icache.ts
src/core/middleware/intersection.ts
src/core/middleware/theme.ts
src/testing/mocks/middleware/icache.ts
src/testing/mocks/middleware/intersection.ts
tests/core/unit/middleware/block.ts
tests/core/unit/middleware/cache.ts
tests/core/unit/middleware/focus.ts
tests/core/unit/middleware/icache.ts
tests/core/unit/middleware/intersection.ts
tests/core/unit/middleware/resize.ts
tests/core/unit/middleware/theme.ts

Add optional parameter to the `icache` middleware set APIs to skip invalidation. Invert the dependency between the `cache` and `icache` so the `cache` can be deprecated. Includes a deprecation message on use of the `cache` middleware
Updates the documentation to reflect the changes made.
Resolves #616 
Resolves #617

Deprecate cache middleware and add optional flag to skip invalidation with the icache

---

src/core/animations/cssTransitions.ts
tests/core/unit/animations/cssTransitions.ts

Adding support for multiple class names in the enter/exit animation properties. This should let us use these properties with theming.
```tsx
<div enterAnimation="class1 class2" exitAnimation="class3 class4" />
```
Resolves #624

Adding support for multiple css transition classes

---

tests/i18n/unit/i18n.ts

**Type:** bug
Resolves #603 
Update the `i18n#setLocaleMessages` tests to reset any custom locale messages to avoid failures in subsequent tests. For example, while `en-GB` is not explicitly supported by the test message bundle, one of the `setLocaleMessages` tests adds support for `en-GB`, resulting in test failures when the suite is run on a machine with `en-GB` set as the primary language.

Fix: reset `setLocaleMessages` calls after tests

---

docs/en/creating-widgets/supplemental.md
docs/en/middleware/supplemental.md
docs/zh-CN/creating-widgets/supplemental.md
docs/zh-CN/middleware/supplemental.md
src/routing/ActiveLink.ts
src/routing/Outlet.ts

**Type:** bug
`cache` middleware has been deprecated, this converts all existing usages of `cache` to `icache`.

Convert cache usages to icache

---

docs/en/middleware/supplemental.md
src/core/middleware/inert.ts
src/shim/util/amd.ts
tests/core/support/jsdom-plugin.ts
tests/core/unit/middleware/all.ts
tests/core/unit/middleware/inert.ts
tests/shim/functional/amd.ts

An `inert` middleware that leverages the `inert` shim to provide an API for setting inert on a node or inverting the inert to all elements attached to the node's parent except the node associated with the passed key. This enables trapping focus for scenario such as a dialog in combination with using the special `body` tag.
```tsx
inert.set('my-dialog', true, true);
<body>
<div key="my-dialog">
<input></input>
</div>
<button onclick={() => { inert.set('my-dialog', false, true)}}>Close</button>
</body>
```

Inert middleware

---

src/testing/mocks/middleware/focus.ts
tests/testing/unit/mocks/middleware/all.ts
tests/testing/unit/mocks/middleware/focus.tsx

This adds a focus middleware mock that is capable of mocking the return value of the middleware's `isFocused` method.
```tsx
const focusMock = createFocusMock();
const factory = create({ focus });
const App = factory(({ middleware: { focus } }) => {
return <div key="root">{focus.isFocused('root') ? 'focus' : 'no focus'}</div>;
});
const h = harness(() => <App />, { middleware: [[focus, focusMock]] });
focusMock('root', false);
h.expect(() => <div key="root">no focus</div>);
focusMock('root', true);
h.expect(() => <div key="root">focus</div>);
```
Resolves #627

Add focus middleware mock and tests

---

src/testing/mocks/middleware/validity.ts
tests/testing/unit/mocks/middleware/all.ts
tests/testing/unit/mocks/middleware/validity.tsx

This adds a validity middleware mock and tests for it.
```tsx
const App = factory(({ middleware: { validity } }) => {
const { valid, message } = validity.get('test', 'test value');
return !valid ? <div>{message}</div> : <div>valid</div>;
});
validityMock('test', { valid: false, message: 'test message' });
let h = harness(() => <App />, { middleware: [[validity, validityMock]] });
h.expect(() => <div>test message</div>);
```
Resolves #630

Add validity middleware mock and tests

---

src/core/vdom.ts
tests/core/unit/vdom.tsx

**Type:** bug
Do not use a body node to as the insert before when inserting nodes into an existing tree.
Resolves #636

Fix inserting a node before a body tag with other siblings

---

src/core/interfaces.d.ts
src/core/middleware/i18n.ts

This PR prevents i18n middleware users from passing keys that aren't part of the bundle messages to the format function.
Resolves #591

Type i18n format function using the passed bundle message keys 

---

src/core/vdom.ts
tests/core/unit/vdom.tsx

**Type:** bug
If the `childDomWrapperId` is not available when trying to find the correct node to insert before, try to find the wrapper id again.
Resolves #641

Ensure childDomWrapperId is available to insert nodes in the correct order

---

src/core/middleware/focus.ts
tests/core/unit/middleware/focus.ts

**Type:** bug 
Backport of #583

V6 - Bug: Fix calling invalidate when checking is a widget or node should focus

---

src/core/vdom.ts
tests/core/unit/vdom.tsx

Support a `null` `domNode` on mount, if `null` is received then it will default to the document body but output a warning when in dev mode (as usually `null` will be received when a dom node using `getElementById` could not be found).

Support accepting null on mount

---

docs/en/middleware/supplemental.md
src/core/vdom.ts
tests/core/unit/vdom.tsx

One use case for `diffProperty` is to be able to influence the property value when executing the diff property callback. For example in the `theme` middleware, it adds an optional `theme` property to a widget that will be used over the currently loaded theme in the injector. However if no property is explicitly passed to the widget, the `theme` property should be set to the injected theme and available in the downstream widget.

Enable diffProperty to influence widget properties

---

src/core/interfaces.d.ts
src/core/vdom.ts
tests/core/unit/vdom.tsx

A chained `.key` function that enables middleware and widgets to specify property names that are considered "primary keys" to be used as the `key` for the widget itself. This means that the author a widget can control the when it will be recreated by the Dojo rendering engine based on changes to properties.
Resolves #658

Specify a property that is used as key for a widget

---

src/core/interfaces.d.ts
src/core/middleware/focus.ts
src/core/mixins/Focus.ts

- move FocusProperties from mixins/Focus to core/interfaces
- export FocusProperties from mixins/Focus
- export FocusProperties from middleware/focus
Resolves #667

Move FocusProperties to interfaces and export from mixin and middleware

---

docs/en/creating-widgets/supplemental.md

Adds a section in the docs on `.key('id')` usage.

Update to the creating widgets docs for defining a widgets primary key property

---

src/core/interfaces.d.ts
src/core/vdom.ts
tests/core/unit/vdom.tsx

Wraps functions passed to a widget to provide a proxy to the latest version.
Resolves #664

Provide a live binding to the current version of a widgets function properties

---

docs/en/middleware/supplemental.md
docs/en/testing/supplemental.md
src/core/middleware/validity.ts

- Add docs for validity middleware
- Add docs for validity middleware mock
- Add docs for focus middleware mock
- Add missing tsx type to breakpoint middleware code fence in docs
- export validity mock as a named export, in addition to the default export
Resolves #638 
Resolves #639

Add docs for validity middleware, validity middleware mock, and focus middleware mock

---

src/core/WidgetBase.ts
src/core/interfaces.d.ts
tests/core/unit/vdom.tsx

**Type:** bug
Fix typings for children using tsx with class based widgets.
Resolves #670

Support a mixture of arrays and single children for class based widgets using tsx

---

docs/en/creating-widgets/supplemental.md
docs/en/i18n/introduction.md
docs/en/stores/introduction.md
docs/en/stores/supplemental.md
docs/en/testing/supplemental.md

This moves the documentation on provided middleware mocks to the Mocking section under Testing, rather than being under the harness section. However, I did add a link to the harness section to make it easy to navigate.
- Move mock middleware documentation to Mocking section
- Fix typos and spelling issues seen in other docs
Resolves #632

Small docs reorg and fix spelling mistakes

---

src/i18n/i18n.ts

**Type:** bug
Sets a default for the `computedLocale` as the existing `''` causes messages to return as undefined. This did not surface in testing as it the computed locale was always being set via `setLocale` however when using this downstream with dojo/widgets the tests were not able to return the default message bundles.

An empty computed locale causes message values to be undefined

---

package-lock.json
src/i18n/i18n.ts
tests/i18n/unit/i18n.ts

**Type:** bug
* Use a basic message loader when i18n has not been configured for the application.
* Load the fallback cldr for unknown locales that are passed to localizeBundle but not set through changing the local via the i18n middleware or mixin.

Fallback to the root bundle when no locales are configured

---

src/core/vdom.ts
tests/core/unit/vdom.tsx

Adds `unmount` to the `renderer` to fully detached and unmount an entire application.
Resolves #676

Unmount Application

---

docs/en/creating-widgets/supplemental.md

Add section to docs for `unmount`

Add docs for `unmount` API

---

src/core/mixins/Themed.ts
tests/core/unit/mixins/Themed.ts

**Type:** bug
Use `auto` over `shallow` for the diff type of `theme`, `classes` and `extraClasses` in the `Themed`  mixin to prevent unnecessarily invalidating when `undefined` is explicitly passed to a widget.
Resolves #609

Change diff type for Themed Mixin to `auto`

---

.travis.yml
package-lock.json
src/core/interfaces.d.ts
src/core/middleware/data.ts
src/core/resource.ts
tests/core/unit/all.ts
tests/core/unit/middleware/all.ts
tests/core/unit/middleware/data.tsx
tests/core/unit/resource.ts

Adds a data middleware capable of making widgets data aware and able to deal with a resource.
- When using the middleware, `resource` will be added to the widget's properties. This can be used to pass a resource to be interacted with.
- Provides `createDataMiddleware` function which takes a generic to determine the type of data the widget requires, this adds a `transform` function to the widget properties which uses the generic to ensure the correct data type is supplied.
*Data middleware API interface:*
- getOrRead(options: ResourceOptions): any;
- getTotal(options: ResourceOptions): number | undefined;
- isLoading(options: ResourceOptions): boolean;
- isFailed(options: ResourceOptions): boolean;
- …

Data middleware and resource

---

src/core/middleware/i18n.ts
src/i18n/i18n.ts
tests/core/unit/middleware/i18n.tsx

**Type:** bug
The i18n middleware should set the locale property to be the computed locale from the default locale that has been set.

Return the current locale if no locale is set via properties or injector

---

docs/en/middleware/supplemental.md
docs/zh-CN/middleware/supplemental.md
src/core/middleware/icache.ts
tests/core/unit/middleware/icache.ts

**Type:** bug
Call `invalidate` for `delete` and `clear` `icache` APIs with an option to skip invalidation mirroring the `set` API
Resolves #663

Invalidate for clear and delete on icache

---

src/routing/ActiveLink.ts
tests/routing/unit/ActiveLink.ts

Include query params when checking if a link is considered active.
Resolves #697

Active link on query param matches

---

package-lock.json
src/core/interfaces.d.ts
src/core/middleware/theme.ts
src/core/mixins/Themed.ts
tests/core/unit/middleware/theme.tsx
tests/core/unit/mixins/Themed.ts

Adds ability to pass both a theme and a variant to widgets via theme middleware / mixin
Related to: https://github.com/dojo/framework/issues/683

Add Theme variants

---

src/core/resource.ts
tests/core/unit/resource.ts

**Type:** bug
This PR fixes an issue where the data total was not being set when `set` was used to side-load the resource data. 
Resolves #700

Set total when side-loading data into a resource

---

src/core/middleware/data.ts
tests/core/unit/middleware/data.tsx

**Type:** bug
Checks to see if a single transform value is specified and if so copies rather than converting to a string and joining.
Resolves #702

Stop data transform from converting values to strings when not required

---

docs/en/creating-widgets/supplemental.md

Updated the documentation by adding a blurb about property diffing.
Resolves #656

Updating documentation around property diffing (#656)

---

src/core/interfaces.d.ts
src/core/middleware/theme.ts
src/core/mixins/Themed.ts
tests/core/unit/middleware/theme.tsx

Rename `css` to `theme` for the `ThemeWithVariant` / `ThemeWithVariants` interfaces.

Rename css to theme for ThemeWithVariant / ThemeWithVariants

---

src/core/ThemeInjector.ts
src/core/interfaces.d.ts
src/core/middleware/theme.ts
src/core/mixins/Themed.ts
tests/core/unit/mixins/Themed.ts

**Type:** bug
Support setting variants via the theme injector.

Support setting variant through the theme injector

---

src/core/vdom.ts
tests/core/unit/vdom.tsx

**Type:** bug
Widgets can end up rendering twice during a single scheduled render which can cause issues with the rendered dom and cause unnecessary processing. This happens when the widget and a parent of a widget is invalidated and ends up rendering due to a property changes or being marked as dirty - then during the render something marks the widget dirty again which means it's rendered again.
The widget should be marked as not dirty _after_ the render and not before.
codesandbox: https://codesandbox.io/s/dreamy-swartz-dco38

Bug: Widgets can render twice during a scheduled render

---

src/core/vdom.ts
tests/core/unit/vdom.tsx

**Type:** bug
Not spreading the properties in vdom when copying them to the wrappers properties can allow users to inadvertently mutate the property object so the diff fails and widgets are not updated as expected.

Spread widget properties in vdom

---

src/core/registerCustomElement.ts
tests/core/support/util.ts
tests/core/unit/registerCustomElement.ts

Adding custom element support for (some) child functions.  
The following scenarios are supported now,
```tsx
<Foo>
{ () => <Bar /> }
</Foo>
```
```html
<element-foo>
<element-bar></element-bar>
</element-foo>
```
```tsx
<Foo>
{{ 
bar: <Bar />, 
qux: [<Qux />, <Qux />]
}}
</Foo>
```
```html
<element-foo>
<element-bar slot="bar"></element-bar>
<element-qux slot="qux"></element-qux>
<element-qux slot="qux"></element-qux>
</element-foo>
```
```tsx
<Foo>
{{ 
bar: () => <Bar />, 
qux: () => <Qux /> 
}}
</Foo>
```
```html
<element-foo>
<element-bar slot="bar"></element-bar>
<element-qux slot="qux"></element-qux>
</element-foo>
```
```tsx
<Foo>
{{
bar: (active) => <Bar active={active} />
}}
</Foo>
```
```html …
```

Custom element slots

---

src/core/ThemeInjector.ts
src/core/registerCustomElement.ts

**Type:** bug
To support themes with variants in custom elements it needs to use the theme injector. At the moment support is restricted to the default variant.

use theme injector for custom elements

---

docs/en/routing/introduction.md
docs/en/routing/supplemental.md
src/routing/ActiveLink.ts
src/routing/Outlet.tsx
src/routing/Route.ts
src/routing/Router.ts
src/routing/interfaces.d.ts
tests/routing/unit/ActiveLink.ts
tests/routing/unit/Link.ts
tests/routing/unit/Outlet.tsx
tests/routing/unit/Route.ts
tests/routing/unit/Router.ts
tests/routing/unit/RouterInjector.ts
tests/routing/unit/all.ts

Changes the concept of an `Outlet` to support rendering multiple matching "routes" to a single outlet. Now using an outlet gives flexibility to render views for an application's routes in a more natural layout, reduces repetitive uses of an `Outlet` that duplicate layout and logic.
The existing `Outlet` behaviour has been moved to `Route` that more accurately describes its behaviour.
Resolves #715

Support rendering multiple routes to an Outlet

---

package-lock.json
package.json
src/core/middleware/data.ts
src/core/middleware/focus.ts
src/core/middleware/theme.ts
src/shim/array.ts
src/shim/object.ts
src/stores/process.ts
src/testing/mocks/middleware/focus.ts
tests/core/functional/meta/Drag.ts
tests/core/unit/middleware/data.tsx
tests/core/unit/middleware/focus.ts
tests/core/unit/middleware/i18n.tsx
tests/core/unit/mixins/I18n.tsx
tests/core/unit/vdom.tsx
tests/shim/unit/array.ts
tests/stores/unit/StoreInjector.ts
tests/stores/unit/StoreProvider.ts

Upgrade to TS 3.8

---

src/core/I18nInjector.ts
src/core/middleware/i18n.ts
src/core/mixins/I18n.ts
src/i18n/i18n.ts
tests/core/unit/middleware/i18n.tsx

**Type:** bug
When i18n is set to an empty state it should clear the injected values and reset the locale back to the computed locale. Currently the injector is being cleared but the actual locale is not being reset to the initial locale.

Allow i18n to be reset to an empty state

---

src/routing/Router.ts
src/routing/interfaces.d.ts
tests/routing/unit/Router.ts

Adds support for setting the `document.title` on route change. This can be done either statically in the route configuration, a callback passed to the router to dynamically set the title or a combination of the two.
> routes.ts
```ts
export default [
{
id: 'foo',
path: 'foo/{param}?{queryParam}'
outlet: 'foo',
title: 'Foo Title'
}
];
```
```ts
registerRouterInjector(routes, registry, {
setDocumentTitle: ({ title, id, params, queryParams }) => {
if (outlet === 'dynamic-title-outlet') {
return `${id}-${params.id}-${queryParams.bar}`;
}
return title;
}
});
```
Currently the options interface for the `setDocumentTitle` look like:
```ts
export interface DocumentTitleOptions {
title?: string;
id: string;
params: …
```

Set document title on route change

---

docs/en/custom-elements/introduction.md
docs/en/custom-elements/supplemental.md

Adding a custom element reference guide for new Dojo 7 features.
Resolves #723

Adding custom element reference guide (#723)

---

src/routing/Link.ts
tests/routing/unit/Link.ts

In order to support on-demand BTR when not in static mode the link should let the browser deal with the routing navigation.
Related to https://github.com/dojo/cli-build-app/issues/367

Let the browser deal with url changes when in BTR and using the CLI serve

---

docs/en/testing/introduction.md

Small fix to the grammar of the testing intro docs

Small fix to the testing introduction

---

src/routing/Router.ts
tests/routing/unit/Router.ts

**Type:** bug
Use the route id and not outlet for the default route.
Resolves #736

Fix default route

---

src/core/middleware/data.ts

**Type:** bug
Fixes the typings of the `resource` property on the data middleware. It should not accept an array of data.
Resolves #740

Fix typings for the resource property

---

src/core/middleware/icache.ts
src/testing/mocks/middleware/icache.ts
tests/core/unit/middleware/icache.ts
tests/testing/unit/renderer.tsx

Enhances the `icache` set behaviour to inject the current cache value if passed a function, and always returns the value from set.
Resolves #739 
Resolves #738

Inject current value to icache on when set when passed a function

---

src/core/has.ts
src/core/vdom.ts
src/shim/array.ts
tests/shim/unit/array.ts
tsconfig.esm.json
tsconfig.json

* Adds a shim for `array.flat` and `array.flatMap` in `@dojo/framework/shim`
* Uses `flat` in `tsx` to flatten the children passed.

Shim for `array.flat` and `array.flatMap` and use `flat` to spread tsx children

---

src/core/ThemeInjector.ts
src/core/interfaces.d.ts
src/core/middleware/theme.ts
src/core/mixins/Themed.ts
tests/core/unit/middleware/theme.tsx
tests/core/unit/mixins/Themed.ts

**Type:** bug
Normalise the `ThemePayload` API to ensure that enough information stored to be able to pass everything back when using `themeContext.get()` or the middleware `theme.get()`.
This now always stores the `theme` but also stores the current `variant` with the name and the variant contents.
If the theme does not have any variants then it will be just the theme stored under `theme`. This is a breaking change, as it never used to be wrapped in an object.

Normalise the theme context

---

src/core/ThemeInjector.ts
src/core/mixins/Themed.ts

**Type:** bug
Missed a scenario where the theme context could be undefined for the Themed mixin. Resolves the current failing test on master.

Fix error when no theme is injected

---

src/core/vdom.ts

**Type:** bug
Optimise operation to find DOM nodes for parent wrappers. It was extremely inefficient when working with large numbers of children. Also moves the call-site out of the `DNode` processing pipeline into the DOM node processing pipeline so it is only called when required, instead of for every single widget.
Existing tests cover the scenarios required for `childDomWrapperId` usage.
Profiles of the existing vdom (left) versus the updated vdom (right) using app with a few thousand children:

Optimise bottleneck finding dom node on parent wrappers in vdom

---

src/core/registerCustomElement.ts
tests/core/unit/registerCustomElement.ts

Support setting a theme variant for custom elements.

Support changing variants for custom element themes

---

src/core/registerCustomElement.ts
tests/core/unit/registerCustomElement.ts

Adding JSON serialization to custom element properties. Any property that is not an attribute will have it's new value deserialized as JSON. If the result is valid, it will be set as the property value.  If the result is not valid, it will be ignored.
Resolves #748

Adding JSON deserialization to custom element properties (#748)

---

src/core/middleware/icache.ts
src/testing/mocks/middleware/icache.ts

**Type:** bug
This allows the icache api to be used after destructuring without binding scope.

Remove referencing `this` from icache api

---

docs/en/resources/introduction.md
docs/en/resources/supplemental.md
src/core/middleware/data.ts
src/core/resource.ts
src/core/vdom.ts
tests/core/unit/middleware/data.tsx
tests/core/unit/resource.ts
tests/core/unit/vdom.tsx

Simplifies using memory resources with Dojo Resource and provides a built in mechanism using custom in memory data.
* Strongly types the resource type to the create resource and the shape of the data that can be passed
* By default creates a memory template for a resource when no custom template is passed
* Exports utility functions for creating memory template
Also includes a change to support this change in vdom's custom diffProperty process. Enables users to return back the original function, that will replace the default wrapped function that gets created.

Simplify using memory resources and data with Dojo Resources

---

package-lock.json
package.json
src/core/ThemeInjector.ts
src/core/has.ts
src/shim/cssVariables.ts
src/shim/util/amd.ts

The recent theming system enhancement to support "variants" posed challenges to provide support for IE11 (with no native support for CSS variables). Initially these were thought to be solved by using a css variable polyfill for all legacy Dojo application builds, however through testing, this failed for at least a few major reasons:
1) The polyfill did not correctly support adding a new class that required CSS variables.
1) The polyfill added additional classes to the DOM nodes which is problematic Dojo's vdom, as it that takes control of node level changes (and does not know about the additional classes)
1) The polyfill is extremely slow due to the use of Mutation Observer, needed to detect changes to the DOM …

Add support to process variant css variables when not supported by the browser

---

src/core/middleware/theme.ts
tests/core/unit/middleware/theme.tsx

**Type:** bug
Changes to stop the `theme` middleware using `diffProperty` to augment a widgets `theme` property with a globally configured theme. Currently the `theme` middleware assumes that the `properties().theme` value is always correct (either the explicitly passed theme or the globally injected theme), which is problematic if the `theme.set(` api is called during a render (for example initially setting the theme). 
The `theme` property should only need to be used to pass onto a child widget (to ensure they use an explicitly passed theme if one is passed to the parent), otherwise only the middleware APIs should be used to work with themes. Internally the `theme` middleware has been changed to pick the theme to use by …

Do not return global injected theme as the theme property

---

src/testing/harness/harness.ts
src/testing/renderer.ts
tests/testing/unit/harness/harness.tsx
tests/testing/unit/renderer.tsx

**Type:** bug
Adds support to both the harness and test renderer for `diffProperty` functions that return values.

Harness and test renderer support diffProperty functions that return values

---

src/testing/decorate.ts
tests/testing/unit/renderer.tsx

**Type:** bug
Allows the `renderer` to handle diffing widgets where a property was passed `null` or `undefined`

Handle undefined properties in renderer diffs

---

src/routing/Router.ts
src/routing/interfaces.d.ts
tests/routing/unit/Router.ts

Adds a `resetScroll` option that calls `scroll(0,0)` on the passed or global window when a route change is emitted.
Resolves #615

Reset scroll on route change

---

src/testing/harness/harness.ts
src/testing/renderer.ts

**Type:** bugfix
This pull request updates the test harness and the test renderer to use the `uuid` module instead of locally-incremented numerical IDs for middlewares so that they can be used in parallel without potential ID collision.
Resolves #776

fix: use UUID middleware IDs in harness and renderer

---

src/testing/renderer.ts
tests/testing/unit/renderer.tsx

**Type:** bug
The params for functions called by `property()` in the test renderer should all be passed to down to the function.
Resolves #786

Pass all params through to the function using `renderer.property()`

---

src/core/diff.ts
src/core/middleware/resources.ts
tests/core/unit/middleware/resources.tsx

**Type:** bug 
Fix the diff used for resource's options and use the correct property for `changed`. This includes changing `shallow`  to use `auto` internally to correctly diff if a non array/object is hit before the maximum depth has been reached (required for the options diff fix)
Resolves #785 
Resolves #788

Fix the diffing for resource options

---

src/core/middleware/resources.ts

**Type:** bug
Do not export `createResource`

create resource should not be exported

---

src/testing/assertRender.ts
tests/testing/unit/assertRender.tsx

**Type:** bug
Fix object and boolean formatting for assertions.

Fix boolean and property object formatting

---

docs/en/resources/introduction.md
docs/en/resources/supplemental.md

A series of docs changes to correct grammar and make the content more readable.
Includes one sample code fix as well.

Resource verbiage changes

---

src/core/vdom.ts
tests/core/unit/vdom.tsx

Adds built in support for adding nodes to the document `head` controlled by the rendering engine. The support is a mirror of the support for adding nodes to the document body.
Resolves #804

Support special head tag for rendering node in the document head

---

.github/workflows/ci.yml
src/core/vdom.ts
tests/core/unit/vdom.tsx

V7 Backport: support special head tag for rendering node in the document head (#805)

---

src/core/interfaces.d.ts
src/core/vdom.ts
tests/core/benchmark/app/Row.ts

**Type:**feature
Expands on the work in #795 to add intrinsic element types for a bunch of other elements.
Resolves #735

Intrinsic element types

---

src/testing/renderer.ts
tests/testing/unit/assertRender.tsx
tests/testing/unit/assertion.tsx

**Type:** bug
Now functional children are executed and replaced with the resulting node when finding nodes for assertion updates.
Resolves #775

Allow finding and modifying wrapped widgets in functional children

---

src/core/interfaces.d.ts
src/core/vdom.ts
src/testing/assertRender.ts
src/testing/harness/support/assertRender.ts

This would accept numbers as DNodes and render them.  This seems straightforward so I'm not sure if there's any other reason we wouldn't want to allow this. I don't think we'd want to render booleans this way given the utility of the common `boolean && node` pattern.
Resolves #761

Allow numbers in vdom

---

src/testing/renderer.ts
tests/testing/unit/assertRender.tsx
tests/testing/unit/assertion.tsx

**Type:** bug
This expands the types for `insertBefore/insertAfter`. This would I believe be a backwards compatible fix but I think may be the appropriate fix in general.
We currently allow inserting before/after at the root and when the parent is not wrapped, and requiring a parent would break both of those use cases. Making the parent argument optional could allow the user to opt into typing but seems klugey since the parent isn't actually needed.
Additionally the only concern with widening the type is that we'd allow the parent's child type to be violated, but even if we enforced it here the `replace` function accepts any DNode. It seems inconsistent if our API enforces the types of siblings but not the node itself. 
Resolves …

Expand types for insert after/before

---

src/core/interfaces.d.ts
src/core/middleware/icache.ts
src/core/middleware/resources.ts
src/core/vdom.ts
src/testing/harness/harness.ts
src/testing/renderer.ts
tests/testing/unit/mocks/middleware/icache.tsx

**Type:** bug
When factories are used to create middleware to print typings we don't need to actually create the middleware-factory every time, only stamp the type on the returned middleware-factory type.
Resolves #817

Add function to create "typed" version of middleware

---

src/core/vdom.ts

Moves the JSX typings to the `tsx` function namespace and avoid clashes on the global namespace, this enables using Dojo with TSX with other frameworks that support `TSX`. Technically this is not a breaking change as the `tsx` function always needs to be imported as `import { tsx } from '@dojo/framework/core/vdom';`
Resolves #46

Move JSX types to `tsx` namespace

---

src/core/vdom.ts
tests/core/unit/vdom.tsx

**Type:** bug
Ensure that `head` and `body` nodes are not used as insert before candidates. 
Resolves #809

Fix: Rendering for multiple nested `head` and `body` nodes

---

src/core/interfaces.d.ts

**Type:** bug
Allows "menu" for button type attribute

Add menu to button type type

---

src/testing/harness/harness.ts
src/testing/renderer.ts
tests/testing/unit/harness/harness.tsx
tests/testing/unit/mocks/middleware/icache.tsx

**Type:** bug
`Exclude<keyof X, 'Y'>` returns a unioned string type not the object type. Normally using `Omit` or `Pick` would fix that but In the case of the MiddlewareResultFactory the type is `never` becuase the call signature isn't a key.
This changes the mocked middleware type to the call signature itself.

Fix mock middleware types

---

src/core/vdom.ts
src/testing/renderer.ts
tests/core/unit/vdom.tsx
tests/testing/unit/assertRender.tsx
tests/testing/unit/assertion.tsx

Backports of #802, #812 and #818

V7 Backports

---

docs/en/i18n/introduction.md
docs/en/i18n/supplemental.md

- clarifies shape of extra locale exports
- mentions dependency on cldr-date
- mentions that browser locale will be used if locale not explicitly set 
Resolves #811

Add further context to i18n documentationand mention cldr-data dep

---

docs/en/i18n/introduction.md

Prettier on i18n introduction doc

---

docs/en/routing/introduction.md
src/routing/Route.ts
src/routing/Router.ts
src/routing/interfaces.d.ts
tests/routing/unit/Route.ts
tests/routing/unit/Router.ts

A proposed implementation of wildcard routing
* A wildcard route is indicated by `*`. It will match a route normally up until the asterisk and then match anything after that.
* A slightly higher penalty is imposed on the route `score` than for a route param, so that a more specific route will always win.
* Introduces the `wildcard` route type and `wildcardSegments` to the `RouteContext` and `MatchDetails`. This will include all the segments of the path matched by the asterisk.
* Adds additional checking for `wildcard` routes so that a change in route segments triggers a route change, even if the same wildcard route is still matched.
Resolves #330

Wildcard routing

---

src/testing/decorate.ts
tests/testing/unit/renderer.tsx

**Type:** bug
Allows finding wrapped nodes when the actual array has additional children that are undefined or booleans.
This fix resolves the failure that led to #839 being created, but the actual bug was not what we originally thought.
Resolves #839

Handle ignored children in decorate

---

src/core/registerCustomElement.ts
tests/core/unit/registerCustomElement.ts

Framework changes as described in #770

Custom element updates for dynamic loading

---

src/testing/renderer.ts
tests/testing/unit/renderer.tsx

Wraps children result in array if not already in one. This fixes tests that fail with single children when using the `mjs` files.
Resolves #843

Wrap children result in an array if not already in one

---

src/core/interfaces.d.ts
src/core/vdom.ts
tests/core/unit/vdom.tsx

Adds two new APIs for the `dom` pragma, `onUpdate` and `onDetach` that are called when the dom node is updated and removed respectively. This will enable support for integrations such as mounting a react component within a Dojo application.
Resolves #828

Enhancement: `onUpdate` and `onDetach` APIs for `dom` pragma

---

src/testing/decorate.ts
src/testing/renderer.ts
tests/testing/unit/assertRender.tsx
tests/testing/unit/assertion.tsx

**Type:** bug
This properly calls and compares functions that are not part of objects, resolving the other part of #775 that was missed by the previous fix
Resolves #775

Fix non-object functional child case for modifying wrapped children in test renders 

---

src/testing/renderer.ts
tests/testing/unit/renderer.tsx

**Type:** bug
Adds support to find nodes in named children that are render results.
Resolves #853

Support setting properties on named children that are a render result for assertions

---

src/testing/renderer.ts
tests/testing/unit/renderer.tsx

This should make it easier to test things that leverage the middleware id, by not using a `uuid` and instead using the middleware key itself which is unique enough for the widget under test.

Use the middleware key as the middleware id in the test renderer

---

docs/en/resources/supplemental.md

**Type:** bug
Fixes incorrect resource docs

Fix incorrect resource example

---

src/routing/Outlet.tsx

**Type:** bug
Adds missing Map shim to Outlet

Add map shim to Outlet

---

src/core/middleware/resources.ts
tests/core/unit/middleware/resources.tsx

**Type:** bug
When a resource is reused with the same id in a newly created widget instance then the we need to process the init options.

Ensure that resources are correctly initialised even if the resource already has been previous created.

---

docs/en/middleware/supplemental.md
src/core/middleware/icache.ts
tests/core/unit/middleware/icache.ts

In  order to be able to determine the status of an async `icache.set`/`icache.getOrSet` this new API, `.pending` returns if the promise is still unresolved.

`pending` API to expose the state of asynchronous icache setters

---

src/core/middleware/icache.ts
tests/core/unit/middleware/icache.ts

In order to be able to react to a "pending" state of an `icache` value we need to call invalidate at the start of calling the async setter and then also on the resolution.

Invalidate for async setting of icache

---

docs/en/resources/introduction.md
docs/en/resources/supplemental.md
src/core/middleware/resources.ts
tests/core/unit/middleware/resources.tsx

Merges createResourceTemplate, createResourceTemplateWithInit and createMemoryResourceTemplate in a single `createResourceTemplate` function that supports creating templates with and without init options and defaults to the old "memory template" which is not going to be called the "default template".
Resolves #864

Refines the create template function APIs

---

docs/en/routing/supplemental.md
src/routing/Router.ts
src/routing/interfaces.d.ts
tests/routing/unit/Router.ts

Adds support for configuring a redirect for routes in the configuration.

Support redirect in routing configuration

---

src/routing/Router.ts
src/routing/history/HashHistory.ts
src/routing/history/MemoryHistory.ts
src/routing/history/StateHistory.ts
src/routing/interfaces.d.ts
tests/routing/unit/Router.ts
tests/routing/unit/history/HashHistory.ts
tests/routing/unit/history/MemoryHistory.ts
tests/routing/unit/history/StateHistory.ts

**Type:** bug
For redirecting on application load the router needs to make sure the history manager instance is set before processing the initial path in case it requires a redirect (which needs the history instance).
This is breaking as it requires introducing a "start" function to the history managers.

Fix redirect on an application load

---

src/routing/Router.ts
src/routing/history/HashHistory.ts
src/routing/history/MemoryHistory.ts
src/routing/history/StateHistory.ts
src/routing/interfaces.d.ts
tests/routing/unit/Router.ts
tests/routing/unit/history/HashHistory.ts
tests/routing/unit/history/MemoryHistory.ts
tests/routing/unit/history/StateHistory.ts

**Type:** bug
For `redirect` the new route should replace the current one so that the browser navigation behaves as expected. To support a `replace` feature has been added to both the router and the history managers.

Support replace for the router and history managers

---

src/testing/renderer.ts
tests/testing/unit/assertion.tsx

**Type:** Bug
Resolves #870 
Updates type definitions for `insertSiblings` function

Update insertSiblings type definition

---

src/core/middleware/resources.ts
tests/core/unit/middleware/resources.tsx

Extends dojo resources to support defining and providing custom APIs in a resource template. With additional support for updating/creating data within a resource.
**Creating a template with a custom API**
```tsx
const template = createResourceTemplate<Data, { save: (item: Data) => void }>({
idKey: 'id',
save: (item, controls) => {
controls.push([item]);
}
});
```
**Create resource middleware that defines a custom API**
```tsx
const resource = createResourceMiddleware<Data, { save: (item: Data) => void }>()
```

Support for custom resource APIs

---

src/core/middleware/resources.ts
tests/core/unit/middleware/resources.tsx

Resource templates can be passed down through multiple widgets and as such should support multiple transforms required to get to and from the original data shape.

Support nested transforms when resources are passed down through multiple widgets

---

src/testing/decorate.ts
src/testing/harness/harness.ts
src/testing/harness/support/selector.ts
src/testing/renderer.ts
tests/testing/unit/harness/harness.tsx
tests/testing/unit/renderer.tsx

**Type:** bug
For deferred properties the renderers resolve to the "final", i.e. run the deferred properties twice but it doesn't pass the inserted flag correctly.
This passes the inserted flag as true for the second process.

Pass inserted flag correctly to deferred props in test renderers

---

src/core/middleware/resources.ts
tests/core/unit/middleware/resources.tsx

**Type:** bug
These changes address a few small bugs in the invalidation and caching logic used by resource:
* Use same cache invalidation logic for updating an existing item as used when a "new" item is created
* Fix calling read multiple times after the cache been invalidated
* Decouple the request and the order part of the synthetic id, so we can track the data items associated at a request level

Fix Resources Invalidation Strategy

---

src/core/vdom.ts

As we start to explore other targets such as native, we need to begin decoupling the dom parts from vdom. In the future we can hopefully make vdom have some kind of agnostic "node" structure to work with, but for now that is too big of a change. So this is a small refactoring that allows the user to pass a node api (that similarly maps to the equivalent dom operations) to the mount function.
This would for instance then allow the user to write adapters for writing to something non dom like.
Down the line we'd still have these issues:
* middleware that works on raw dom nodes (I have changed the core `node` middleware to use the passed `nodeApi` but generally the same change would have to happen elsewhere
* the …

Start to decouple dom completely from vdom

---

src/core/middleware/resources.ts
tests/core/unit/middleware/resources.tsx

**Type:** bug
Fixes an error that occurs if get is used for an id that doesn't exist in the resource cache.

Resources: Fix getting for an unknown id

---

src/core/middleware/resources.ts
tests/core/unit/middleware/resources.tsx

Pass `get` control to the templates to be able to return items by request or ids

Resources: Pass get control to template

---

src/core/middleware/inert.ts
tests/core/unit/middleware/inert.ts

**Type:** bug
This only adds/removes the inert properties to the node when the options have changed when calling the middleware

Only run the inert middleware when the properties have been changed

---

src/core/vdom.ts
tests/core/unit/vdom.tsx

**Type:** bug
Changing how vdom work when setting values on an `input` element. This is to resolve an issue with Safari that jumps the caret to the end of the input when updating the value.
Resolves #886

Make inputs partially only controlled

---

src/core/middleware/resources.ts
tests/core/unit/middleware/resources.tsx

**Type:** bug
The types for inferring the resource data and api types worked well with widgets that did not have properties (like all the tests) but did not work properly for widgets that had custom properties defined (most widgets)

Resources: Deal with inferring resource types from widgets with custom properties

---

src/core/vdom.ts
tests/core/unit/vdom.tsx

**Type:** bug
Virtual nodes should be treated the same as widgets when it comes to hydrating an existing DOM node structure. This means passing the merge node candidates down to when a virtual node is met.

Take in to account virtual nodes when hydrating an existing DOM structure

---

src/testing/renderer.ts
tests/testing/unit/assertion.tsx
tests/testing/unit/renderer.tsx

**Type:** bug
Fix the `child` typings for widgets with optional children and functional children.

Fix the typings for the arguments on the test renderer child api

---

src/testing/assertRender.ts
src/testing/decorate.ts
src/testing/renderer.ts
tests/testing/unit/assertRender.tsx
tests/testing/unit/renderer.tsx

Provides an API to support testing widgets with complex, nested typed children, for example: 
```tsx
interface TypedChildren {
headers: {
headerA: (value: string, num: number) => RenderResult    
},
cells: {
columnA: (value: string) => RenderResult
},
footer: RenderResult
}
```
Currently the test renderer's `child` API enables consumers to instruct the renderer to resolve children to one level, `renderer.child(WrappedWidget, 'child', 'params', 'for', 'renderer');` this change adds an additional overload that enables users to provide params to resolve multiple children, including nested children. The function is typed to require all functional children to have params returned and the params are typed for the …

Support testing widgets with nested typed children

---

src/routing/Router.ts
tests/routing/unit/Router.ts

**Type:** bug
The redirect option on the routing configuration should replace the path instead of setting it otherwise the back browser controls won't work as expected.

Redirect should use replace path not set path

---

docs/en/routing/introduction.md
src/routing/Router.ts
src/routing/interfaces.d.ts
tests/routing/unit/Router.ts

At the moment all query params defined in the routing configuration are considered mandatory, however there are times where a query params is optional but still need the router to generate the link correctly (depending on if the optional query param value is passed).
This changes adds a new `?` indicator if a query param is to be considered optional:
```tsx
{
path: 'my/routes/path?{requiredQueryParam}&{optionalQueryParam?}'
}
```
The `?` before the closing brace tells the router that the param is not required.
Resolves #508

Support optional query params in routing configuration

---

package-lock.json
src/core/mixins/Focus.ts
src/core/mixins/I18n.ts
src/core/mixins/Themed.ts
src/routing/Router.ts
src/shim/array.ts
src/testing/renderer.ts
tests/core/unit/meta/InputValidity.ts
tests/core/unit/middleware/validity.ts
tests/core/unit/waitFor.ts
tests/routing/unit/history/StateHistory.ts
tests/shim/unit/AbortController.ts
tests/stores/unit/process.ts

Small changes to support up to TS 4.1.

Changes for forward compatibility with Typescript 4+

---

src/core/vdom.ts
tests/core/unit/vdom.tsx

**Type:** bug/feature
There is no need to recreate the property function wrapper each render, in addition this is causing issues with the custom element wrapper because the functions will always be referentially different.

Cache the function wrapper, no need to recreate each render.

---

src/routing/Link.ts
tests/routing/unit/Link.ts

**Type:** bug 
We should always forward the target property to the anchor tag for Link.

Link: Always pass the target attribute regardless of whether the event is intercepted

---

src/i18n/i18n.ts
tests/i18n/unit/i18n.ts

**Type:** bug
Always register the locales with the globalize bundles
Resolves #906

Register the messages for all locales
