CONTRIBUTING.md
docs/Committer-Workflow.md
docs/core/UrlSearchParams.md
docs/core/has.md
docs/core/lang.md
docs/core/load.md
docs/core/on.md
docs/core/stringExtras.md
docs/shim/Map.md
docs/shim/Observable.md
docs/shim/array.md
docs/shim/string.md

- update docs
- update CONTRIBUTING.md

Update docs to point to @dojo/framework in example

---

src/shim/global.ts

**Type:** bug
Aligns the ordering of detection to the proposal implementation in the spec: https://github.com/tc39/proposal-global

Check for window before global in global shim

---

README.md
docs/V3-Migration-Guide.md

Adds a migration guide for v2 to v3.

Migration guide

---

src/stores/README.md
src/stores/middleware/localStorage.ts
tests/stores/unit/all.ts
tests/stores/unit/middleware/localStorage.ts

Provides a basic middleware that can be used to persist sections of state to local storage and load data into a store from local storage.
Resolves #64

Local Storage Middleware

---

src/widget-core/mixins/Themed.ts
tests/widget-core/unit/mixins/Themed.ts

When a ThemedWidget doesn't include a base theme a warning will be printed to the console.
Resolves #42

added warn on missing theme

---

package-lock.json

**Type:** bug
Update locked dependencies

Update locked deps to fix issue with istanbul

---

src/core/util.ts
tests/core/unit/util.ts

There is still a case to have basic support for `debounce` and `throttle` in core/utils as they are pretty common requirements, the implementations are simple and we don't want to have to force consumers to roll their own every time or use an external dependency.

Add debounce and throttle back to core/util

---

package-lock.json
src/core/DateObject.ts
src/core/MatchRegistry.ts
src/core/async/Task.ts
src/core/async/iteration.ts
src/core/lang.ts
src/core/on.ts
src/core/request.ts
src/core/request/Response.ts
src/core/request/providers/node.ts
src/core/request/providers/xhr.ts
src/core/util.ts
src/i18n/util/globalize.ts
src/shim/Symbol.ts
src/shim/array.ts
src/shim/math.ts
src/shim/object.ts
src/shim/support/has.ts
src/shim/tslib.ts
tests/core/unit/async/Task.ts
tests/core/unit/async/iteration.ts
tests/core/unit/lang.ts
tests/core/unit/request.ts
tests/i18n/unit/date.ts
tests/i18n/unit/i18n.ts
tests/routing/unit/history/StateHistory.ts
tests/shim/unit/Observable.ts
tests/shim/unit/Promise.ts
tests/widget-core/benchmark/runner/src/benchmarkRunner.ts
tests/widget-core/benchmark/vanillajs-non-keyed/Main.ts

Prefer using `as any` over legacy casting `<any>`.

prefer using 'as any' over legacy casting '<any>'

---

src/has/has.ts

**Type:** bug
Fixed comment at method has().
Resolves #84

fixed issue 84

---

src/widget-core/mixins/Themed.ts

remove unused property

---

docs/V4-Migration-Guide.md

Migration Doc Updates

---

src/core/README.md

**Type:** bug
Update the core README
Resolves #62

Update core readme to reflect the state of the repository

---

package-lock.json
package.json
src/shim/Symbol.ts
src/widget-core/README.md

**Type:** bug
Update SymbolConstructor for Observable to `readonly`.
Resolves #39

Update SymbolConstructor for Observable

---

src/routing/README.md

**Type:** bug
Corrects the routing README
Resolves #143

Update routing README

---

intern.json
package-lock.json
package.json

Upgrade "whatwg-fetch" to 3.0.0 to get new features:
https://github.com/github/fetch/releases/tag/v3.0.0
Resolves #???

Upgrade "whatwg-fetch" to 3.0.0

---

src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

**Type:** bug
Add sibling `order` property to `VNodeWrapper` and `WNodeWrapper`. Use the node order in the invalidation queue sort algorithm, which now sorts by depth and then sibling order.
Resolves #200

Add order to dnode wrapper and use to sort invalidation instructions

---

docs/V5-Migration-Guide.md

An initial v5.0.0 migration guide.

Initial v5.0.0 migration guide

---

README.md

Update badge to Discord rather than Gitter

---

README.md

Make Discord badge match other badges

---

docs/V5-Migration-Guide.md

Update v5 migration guide

---

README.md

Update main readme for 5.0.0 release

Update readme for 5.0.0

---

src/stores/README.md

**Type:** bug
Fixes references to middleware in stores documentation.

Fix references to middleware in store docs

---

src/testing/assertionTemplate.ts
src/testing/support/assertRender.ts
tests/testing/unit/assertionTemplate.tsx

Revert "Assertion Template enhancements"

---

src/widget-core/vdom.ts
tests/widget-core/unit/vdom.ts

**Type:** bug
Back port of #297.

Ensure that nodes are inserted in the correct position when nested within widgets

---

docs/en/styling-and-theming/supplemental.md

**Type:** bug / docs
Resolves an issue found with the Styling and Theming guide while integrating it into dojo site.

Fix language tag for bash/shell commands

---

README.md
package-lock.json
package.json
src/core/QueuingEvented.ts
src/core/util.ts
src/routing/history/StateHistory.ts
src/shim/iterator.ts
src/stores/Store.ts
src/stores/state/ImmutableState.ts
src/widget-core/decorators/customElement.ts
src/widget-core/mixins/Projector.ts
src/widget-core/mixins/Themed.ts
src/widget-core/vdom.ts
tests/routing/unit/ActiveLink.ts
tests/routing/unit/Link.ts
tests/routing/unit/Outlet.ts
tests/routing/unit/history/StateHistory.ts
tests/shim/unit/array.ts
tests/shim/unit/iterator.ts
tests/widget-core/unit/decorators/watch.ts
tests/widget-core/unit/vdom.ts

Update to TypeScript 3.4.5

---

src/core/vdom.ts
tests/core/unit/vdom.ts

Core middleware that returns the scoped registry handler.
Resolves #368

Registry Middleware

---

src/core/vdom.ts
tests/core/unit/vdom.ts

Middleware that provides a hook to register a function that can be used to perform a custom diff on the previous and next properties. If the widget requires re-rendering based on the result of the custom diff then invalidate should be called using the `invalidator` middleware
Resolves #367

Diff Properties Middleware

---

src/core/middleware/dimensions.ts
tests/core/unit/middleware/all.ts
tests/core/unit/middleware/dimensions.ts

Middleware that provides the dimensions of a node for a specified key.
Resolves #399

Dimensions middleware

---

src/widget-core/registerCustomElement.ts
tests/widget-core/unit/registerCustomElement.ts

**Type:** bug
Applies the same fix as #394 to v5

Fix custom element initialization (backport)

---

src/routing/Outlet.ts

**Type:** bug
Only invalidate if the router key changes.

Only invalidate if the router key is different

---

src/core/vdom.ts

**Type:** bug
Instantiate widget meta data lazily when initially used. This prevents using memory unnecessarily.

Lazily construct metadata as needed

---

src/core/vdom.ts
tests/core/unit/vdom.ts

**Type:** bug
Set the correct DOM node against `WNodeWrapper`s, instead of the first DOM node created by children widgets (which could not be the top most DOM node when returning an array).
Resolves #432

Correctly resolve the DOM node associated to a WNode

---

package-lock.json
src/stores/process.ts

**Type:** bug
Back port https://github.com/dojo/framework/pull/336.

v5 - Fix typings for commands created by a command factory

---

docs/V6-Migration-Guide.md

Initial Dojo 6 migration guide.

V6 migration guide

---

docs/en/routing/basic-usage.md
docs/en/routing/supplemental.md

Update routing docs with function-based widget examples

Routing docs update for function-based widgets

---

src/core/middleware/validity.ts
tests/core/unit/middleware/all.ts
tests/core/unit/middleware/dimensions.ts
tests/core/unit/middleware/validity.ts

Implements the `InputValidity` meta as a middleware.

validity middleware

---

src/core/vdom.ts
tests/core/unit/vdom.ts

**Type:** bug
Ensure that nodes created within the `body` tag are detached correctly
Resolves #459

Ensure nodes attached to the body are orphaned

---

docs/V6-Migration-Guide.md

Adds widgets changes to v6 migration doc

Add widgets changes to v6 doc

---

docs/V6-Migration-Guide.md
tests/shim/functional/all.ts
tests/shim/functional/amd.ts
tests/shim/functional/asyncAwait.ts
tests/shim/functional/polyfills.ts
tests/testing/unit/assertionTemplate.tsx

**Type:** bug
Removes a duplicate test.

Remove duplicate test

---

docs/en/creating-widgets/introduction.md
docs/en/creating-widgets/supplemental.md
docs/en/i18n/introduction.md
docs/en/i18n/supplemental.md
docs/en/middleware/supplemental.md
docs/en/outline/introduction.md
docs/en/outline/supplemental.md
docs/en/routing/supplemental.md

**Type:** bug
Add links for the overview.

Add links for the overview

---

docs/en/testing/supplemental.md

**Type:** bug
Address the remaining issue from the documentation feedback.
Resolves #464

Address test doc feedback

---

docs/V6-Migration-Guide.md

Updates migration doc re. `Textarea` -> `TextArea` rename.

rename Textarea to TextArea migration doc update

---

src/core/vdom.ts
tests/core/unit/vdom.ts

**Type:** bug
Resolves https://github.com/dojo/framework/issues/516

Fix nodeMap node handling for node removal and node changes

---

src/core/WidgetBase.ts
tests/shim/unit/math.ts

**Type:** bug
Backport of #539

Ensure that initial properties are set to false (#539)

---

docs/en/testing/supplemental.md
src/testing/mocks/middleware/icache.ts
tests/testing/unit/mocks/middleware/all.ts
tests/testing/unit/mocks/middleware/icache.tsx

Middleware mocking documentation (#537)

---

src/core/vdom.ts

**Type:** bug
Backport of #547

Run distinguishable in sync as only runs on dev mode (#547)

---

docs/zh-CN/middleware/supplemental.md
docs/zh-CN/testing/supplemental.md

Update simplified chinese docs

update simplified chinese docs

---

src/core/registerCustomElement.ts

Updates `registerCustomElement` from using class-based widgets internally to function-based widgets.

Use function-based widget for custom elements

---

docs/zh-CN/building/introduction.md
docs/zh-CN/building/supplemental.md

Translate docs/building to simplified chinese.

translate docs/building to simplified chinese

---

docs/zh-CN/middleware/supplemental.md
docs/zh-CN/outline/introduction.md
docs/zh-CN/outline/supplemental.md

update zh-CN building links (#574)

---

docs/en/building/supplemental.md

Adding a short description of the application base path, and how to configure it!
Resolves #506

Adding blurb about application base path

---

src/core/interfaces.d.ts

Convenience interface for middleware api.

Middleware api interface

---

.codesandbox/ci.json

Add codesandbox ci

---

docs/zh-CN/styling/introduction.md
docs/zh-CN/styling/supplemental.md

Translate docs/styling to simplified chinese

translate docs/styling to simplified chinese

---

package-lock.json
src/testing/assertionTemplate.ts
tests/testing/unit/assertionTemplate.tsx

**Type:** bug
back port of #587

Ensure assertion template children are immutable (#587)

---

package-lock.json
package.json
src/core/has.ts
src/shim/inert.ts
tests/has/unit/has.ts

Add inert shim and feature flag.
Resolves #612

Add inert shim and has feature flag

---

docs/zh-CN/routing/introduction.md
docs/zh-CN/routing/supplemental.md

Translate docs/routing to simplified chinese

Translate docs/routing to simplified chinese

---

docs/zh-CN/i18n/introduction.md
docs/zh-CN/i18n/supplemental.md

Translate docs/i18n to simplified chinese.

Translate docs/i18n to simplified chinese

---

docs/en/middleware/supplemental.md
src/shim/inert.ts

**Type:** bug
Use the dist inert module and update the inert example.

Use dist inert and update doc example

---

package-lock.json
src/core/vdom.ts
tests/core/unit/vdom.tsx

**Type:** bug
Backport of #642

V6 - Ensure childDomWrapperId is available to insert nodes in the correct order

---

docs/en/building/introduction.md

**Type:** bug
Fix the build docs when referencing the `watch` option

Update build docs

---

docs/en/building/supplemental.md

**Type:** bug
Fix the dojo blocks docs

Fix dojo blocks docs

---

docs/en/building/supplemental.md

**Type:** bug
Add the block requirements to the docs.

Fix dojo blocks docs (again)

---

docs/en/building/supplemental.md

**Type:** bug
backport of #649

Fix dojo blocks docs (#649)

---

docs/en/building/introduction.md

**Type:** bug
Backport doc change in #647

fix build docs (#647)

---

package-lock.json
src/core/vdom.ts
tests/core/unit/vdom.tsx

Unmount Application (#680)

---

package-lock.json
src/i18n/i18n.ts
tests/i18n/unit/i18n.ts

**Type:** bug 
Fix sync nls bundles for registered supported locales.

Fix sync nls bundles for supported locales

---

package-lock.json
package.json

Match Cldr version with Globalize

---

src/core/registerCustomElement.ts
tests/core/unit/registerCustomElement.ts

**Type:** bug
Fixing bugs with custom element slots, and cleaning up code.

custom element slot updates

---

docs/V7-Migration-Guide.md

Dojo 7 Migration Guide

---

docs/en/middleware/supplemental.md

Add docs for injecting current value into cache setter

---

docs/en/custom-elements/supplemental.md

A small update to custom element supplemental guide to include a description of the new json deserialization of attributes.

Adding json serialization to custom elements supplemental

---

docs/en/stores/supplemental.md
docs/zh-CN/stores/supplemental.md

**Type:** bug
Fixes a typo in store docs

Fix mistake in docs

---

docs/en/custom-elements/supplemental.md

Updating custom element supplemental docs to include instructions on updating the theme / variant at runtime.

Adding multiple themes and variants to ce supplemental docs

---

docs/en/middleware/supplemental.md
docs/zh-CN/middleware/supplemental.md

**Type:** bug
Fix imports in middleware docs

Fix imports on middleware docs

---

src/core/middleware/drag.ts
tests/core/functional/Drag.ts
tests/core/functional/middleware/drag.html
tests/core/functional/middleware/drag.ts
tests/core/unit/middleware/all.ts
tests/core/unit/middleware/drag.ts

This pull request adds a new module that exposes drag middleware.
Resolves #514 
References https://github.com/dojo/widgets/issues/1429

feat: drag middleware

---

src/testing/assertRender.ts
tests/testing/unit/assertRender.tsx

**Type:** bug
Improve the diff formatting when using the test renderer to support non primitive property values (i.e. objects/arrays), format properties on separate lines to make it easier to see which property is difference and deeply format objects to ensure that that props are sorted for consistent results.
Resolves #783

improve the test renderer diff formatting

---

src/core/middleware/theme.ts

**Type:** bug
The `theme` property has been updated for Dojo 7 to be able to include variants and the active variant, which means the depth has increased. This updates the diff depth to match the maximum expected depth of the theme object.
Resolves #787

Update the diff algorithm and depth for theme and classes

---

src/core/middleware/resources.ts
tests/core/unit/middleware/resources.tsx

**Type:** bug
The data is stored in a sparse array, so when iterating thought the data array in `defaultFind` need to check that the item has been loaded before perform the filter.

Check item exists before filtering in default find

---

docs/en/testing/supplemental.md

Fixed doc typo

---

README.md

* Add links to migration guides for v6 and v7
* Add TS version support for v7
* Update copyright year
**Type:** documentation

README updates for v7 release

---

src/testing/mocks/middleware/block.ts
tests/testing/unit/mocks/middleware/all.ts
tests/testing/unit/mocks/middleware/block.tsx

Adds block middleware mock
Resolves #443

Create block middleware mock

---

tests/testing/unit/assertRender.tsx

**Type:** bug
Fix unit tests for cross browser testing.

Update assert render unit test

---

docs/en/middleware/supplemental.md

Correcting typos in middleware supplemental
Resolves #504

Minor revisions to middleware supplemental (#504)

---

docs/en/stores/supplemental.md

Adding a blurb about process transformers to supplemental store docs.
Resolves #588

Adding documentation about using process transformers #588

---

src/core/interfaces.d.ts
src/core/middleware/icache.ts
src/core/middleware/resources.ts
src/core/vdom.ts
src/testing/decorate.ts
src/testing/harness/harness.ts
src/testing/renderer.ts
tests/testing/unit/assertRender.tsx
tests/testing/unit/assertion.tsx
tests/testing/unit/mocks/middleware/icache.tsx
tests/testing/unit/renderer.tsx

Backports of
#840 #780 #819 #822 #844

V7 Backports

---

src/testing/renderer.ts
tests/testing/unit/renderer.tsx

Bringing https://github.com/dojo/framework/pull/854 into v7!

Backport of harness fix to v7

---

src/core/vdom.ts
tests/core/unit/vdom.tsx

**Type:** bug
Backport of #887

V7 - Make inputs partially controlled

---

docs/en/resources/introduction.md
docs/en/resources/supplemental.md

Updated dojo resource documentation

Update resource introduction

---

CODE_OF_CONDUCT.md

Broken link to code of conduct has been fixed.

Update code of conduct link
